apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
data:
  chat.toml: |
    [node]
        name = "chat"
        host = "0.0.0.0"
        apps = ["chat"]
    [port]
        actor = 19001
        chat = 19003
    [postgres]
        url = "postgresql://postgres:%40zyc0131@host.docker.internal:5432/postgres?sslmode=disable"

    [redis]
        addr = "host.docker.internal:6379"
        password = "@zyc0131"
        db = 0
        dial_timeout = "5s"

    [log]
        path = "/var/log/game"
        level = "all"
        file = "{Y-m-d}.log"
        stStatus = 0

    [registery]
        type = "redis"
    [registery.redis]
        interval = 10

    [metrics]
        addr = ":9091"

    [trace]
        endpoint = "host.docker.internal:4317"
