apiVersion: v1
kind: ConfigMap
metadata:
  name: friend-config
data:
  friend.toml: |
    [node]
        name = "role"
        host = "0.0.0.0"
        apps = ["friend"]
    [port]
        actor = 19001
        friend = 19002
    [postgres]
        url = "postgresql://postgres:%40zyc0131@host.docker.internal:5432/postgres?sslmode=disable"

    [redis]
        addr = "host.docker.internal:6379"
        password = "@zyc0131"
        db = 0
        dial_timeout = "5s"

    [log]
        path = "/var/log/game"
        level = "all"
        file = "{Y-m-d}.log"
        stStatus = 0

    [registery]
        type = "dns"
    [registery.dns]
        # 按实际 namespace 修改: game-svc.<namespace>.svc.cluster.local
        domain = "friend-svc.default.svc.cluster.local"
        interval = 10

    [metrics]
        addr = ":9091"

    [trace]
        endpoint = "host.docker.internal:4317"
