// ID: 28001~28099

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.3
// source: chat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PChatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *PRolePublic           `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PChatMsg) Reset() {
	*x = PChatMsg{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PChatMsg) ProtoMessage() {}

func (x *PChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PChatMsg.ProtoReflect.Descriptor instead.
func (*PChatMsg) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *PChatMsg) GetSender() *PRolePublic {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *PChatMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PChatMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 聊天初始化 (28001) - 登录时自动调用
type ReqChatInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqChatInit) Reset() {
	*x = ReqChatInit{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqChatInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChatInit) ProtoMessage() {}

func (x *ReqChatInit) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChatInit.ProtoReflect.Descriptor instead.
func (*ReqChatInit) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

type RspChatInit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LobbyId        int32                  `protobuf:"varint,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id"`
	WorldMessages  []*PChatMsg            `protobuf:"bytes,2,rep,name=world_messages,json=worldMessages,proto3" json:"world_messages"`
	SystemMessages []*PChatMsg            `protobuf:"bytes,3,rep,name=system_messages,json=systemMessages,proto3" json:"system_messages"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RspChatInit) Reset() {
	*x = RspChatInit{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspChatInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspChatInit) ProtoMessage() {}

func (x *RspChatInit) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspChatInit.ProtoReflect.Descriptor instead.
func (*RspChatInit) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *RspChatInit) GetLobbyId() int32 {
	if x != nil {
		return x.LobbyId
	}
	return 0
}

func (x *RspChatInit) GetWorldMessages() []*PChatMsg {
	if x != nil {
		return x.WorldMessages
	}
	return nil
}

func (x *RspChatInit) GetSystemMessages() []*PChatMsg {
	if x != nil {
		return x.SystemMessages
	}
	return nil
}

// 发送私聊 (28008)
type ReqChatSendPrivate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqChatSendPrivate) Reset() {
	*x = ReqChatSendPrivate{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqChatSendPrivate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChatSendPrivate) ProtoMessage() {}

func (x *ReqChatSendPrivate) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChatSendPrivate.ProtoReflect.Descriptor instead.
func (*ReqChatSendPrivate) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ReqChatSendPrivate) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ReqChatSendPrivate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RspChatSendPrivate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspChatSendPrivate) Reset() {
	*x = RspChatSendPrivate{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspChatSendPrivate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspChatSendPrivate) ProtoMessage() {}

func (x *RspChatSendPrivate) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspChatSendPrivate.ProtoReflect.Descriptor instead.
func (*RspChatSendPrivate) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

// 拉取私聊历史 (28010)
type ReqChatPrivateHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      int64                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqChatPrivateHistory) Reset() {
	*x = ReqChatPrivateHistory{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqChatPrivateHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChatPrivateHistory) ProtoMessage() {}

func (x *ReqChatPrivateHistory) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChatPrivateHistory.ProtoReflect.Descriptor instead.
func (*ReqChatPrivateHistory) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ReqChatPrivateHistory) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *ReqChatPrivateHistory) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RspChatPrivateHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*PChatMsg            `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspChatPrivateHistory) Reset() {
	*x = RspChatPrivateHistory{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspChatPrivateHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspChatPrivateHistory) ProtoMessage() {}

func (x *RspChatPrivateHistory) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspChatPrivateHistory.ProtoReflect.Descriptor instead.
func (*RspChatPrivateHistory) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *RspChatPrivateHistory) GetMessages() []*PChatMsg {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 私聊消息通知 (28012) - 服务端推送
type NotifyChatPrivate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *PChatMsg              `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyChatPrivate) Reset() {
	*x = NotifyChatPrivate{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyChatPrivate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyChatPrivate) ProtoMessage() {}

func (x *NotifyChatPrivate) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyChatPrivate.ProtoReflect.Descriptor instead.
func (*NotifyChatPrivate) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyChatPrivate) GetMessage() *PChatMsg {
	if x != nil {
		return x.Message
	}
	return nil
}

// 拉取系统消息 (28013)
type ReqChatSystemHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqChatSystemHistory) Reset() {
	*x = ReqChatSystemHistory{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqChatSystemHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChatSystemHistory) ProtoMessage() {}

func (x *ReqChatSystemHistory) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChatSystemHistory.ProtoReflect.Descriptor instead.
func (*ReqChatSystemHistory) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *ReqChatSystemHistory) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RspChatSystemHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*PChatMsg            `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspChatSystemHistory) Reset() {
	*x = RspChatSystemHistory{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspChatSystemHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspChatSystemHistory) ProtoMessage() {}

func (x *RspChatSystemHistory) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspChatSystemHistory.ProtoReflect.Descriptor instead.
func (*RspChatSystemHistory) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *RspChatSystemHistory) GetMessages() []*PChatMsg {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 系统消息通知 (28015) - 服务端推送
type NotifyChatSystem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *PChatMsg              `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyChatSystem) Reset() {
	*x = NotifyChatSystem{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyChatSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyChatSystem) ProtoMessage() {}

func (x *NotifyChatSystem) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyChatSystem.ProtoReflect.Descriptor instead.
func (*NotifyChatSystem) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *NotifyChatSystem) GetMessage() *PChatMsg {
	if x != nil {
		return x.Message
	}
	return nil
}

// 发送频道消息 (28020) - 客户端发送 channel_type + content，channel_id 由服务端推断
// channel_type 枚举值定义见策划配置表 chatchannel.xlsx channel_type 列：
//
//	1=世界 2=私聊 3=系统 4=公会
type ReqChatSendChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelType   int32                  `protobuf:"varint,1,opt,name=channel_type,json=channelType,proto3" json:"channel_type"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqChatSendChannel) Reset() {
	*x = ReqChatSendChannel{}
	mi := &file_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqChatSendChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChatSendChannel) ProtoMessage() {}

func (x *ReqChatSendChannel) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChatSendChannel.ProtoReflect.Descriptor instead.
func (*ReqChatSendChannel) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *ReqChatSendChannel) GetChannelType() int32 {
	if x != nil {
		return x.ChannelType
	}
	return 0
}

func (x *ReqChatSendChannel) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RspChatSendChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspChatSendChannel) Reset() {
	*x = RspChatSendChannel{}
	mi := &file_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspChatSendChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspChatSendChannel) ProtoMessage() {}

func (x *RspChatSendChannel) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspChatSendChannel.ProtoReflect.Descriptor instead.
func (*RspChatSendChannel) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

// 频道消息通知 (28022) - 服务端推送
// channel_type 枚举值定义见策划配置表 chatchannel.xlsx channel_type 列
type NotifyChatChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelType   int32                  `protobuf:"varint,1,opt,name=channel_type,json=channelType,proto3" json:"channel_type"`
	ChannelId     int64                  `protobuf:"varint,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id"`
	SenderId      int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyChatChannel) Reset() {
	*x = NotifyChatChannel{}
	mi := &file_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyChatChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyChatChannel) ProtoMessage() {}

func (x *NotifyChatChannel) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyChatChannel.ProtoReflect.Descriptor instead.
func (*NotifyChatChannel) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{13}
}

func (x *NotifyChatChannel) GetChannelType() int32 {
	if x != nil {
		return x.ChannelType
	}
	return 0
}

func (x *NotifyChatChannel) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *NotifyChatChannel) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *NotifyChatChannel) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotifyChatChannel) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 拉取频道历史 (28023)
// channel_type 枚举值定义见策划配置表 chatchannel.xlsx channel_type 列
type ReqChatChannelHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelType   int32                  `protobuf:"varint,1,opt,name=channel_type,json=channelType,proto3" json:"channel_type"`
	ChannelId     int64                  `protobuf:"varint,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqChatChannelHistory) Reset() {
	*x = ReqChatChannelHistory{}
	mi := &file_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqChatChannelHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChatChannelHistory) ProtoMessage() {}

func (x *ReqChatChannelHistory) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChatChannelHistory.ProtoReflect.Descriptor instead.
func (*ReqChatChannelHistory) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{14}
}

func (x *ReqChatChannelHistory) GetChannelType() int32 {
	if x != nil {
		return x.ChannelType
	}
	return 0
}

func (x *ReqChatChannelHistory) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ReqChatChannelHistory) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RspChatChannelHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*PChatMsg            `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspChatChannelHistory) Reset() {
	*x = RspChatChannelHistory{}
	mi := &file_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspChatChannelHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspChatChannelHistory) ProtoMessage() {}

func (x *RspChatChannelHistory) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspChatChannelHistory.ProtoReflect.Descriptor instead.
func (*RspChatChannelHistory) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{15}
}

func (x *RspChatChannelHistory) GetMessages() []*PChatMsg {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x0fgalaxy.protocol\x1a\x11msg_options.proto\x1a\n" +
	"role.proto\"x\n" +
	"\bPChatMsg\x124\n" +
	"\x06sender\x18\x01 \x01(\v2\x1c.galaxy.protocol.PRolePublicR\x06sender\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x15\n" +
	"\vReqChatInit:\x06\xa8\xac\x1d\xe1\xda\x01\"\xb6\x01\n" +
	"\vRspChatInit\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\x05R\alobbyId\x12@\n" +
	"\x0eworld_messages\x18\x02 \x03(\v2\x19.galaxy.protocol.PChatMsgR\rworldMessages\x12B\n" +
	"\x0fsystem_messages\x18\x03 \x03(\v2\x19.galaxy.protocol.PChatMsgR\x0esystemMessages:\x06\xa8\xac\x1d\xe2\xda\x01\"S\n" +
	"\x12ReqChatSendPrivate\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent:\x06\xa8\xac\x1d\xe8\xda\x01\"\x1c\n" +
	"\x12RspChatSendPrivate:\x06\xa8\xac\x1d\xe9\xda\x01\"R\n" +
	"\x15ReqChatPrivateHistory\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x03R\bfriendId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count:\x06\xa8\xac\x1d\xea\xda\x01\"V\n" +
	"\x15RspChatPrivateHistory\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.galaxy.protocol.PChatMsgR\bmessages:\x06\xa8\xac\x1d\xeb\xda\x01\"P\n" +
	"\x11NotifyChatPrivate\x123\n" +
	"\amessage\x18\x01 \x01(\v2\x19.galaxy.protocol.PChatMsgR\amessage:\x06\xa8\xac\x1d\xec\xda\x01\"4\n" +
	"\x14ReqChatSystemHistory\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count:\x06\xa8\xac\x1d\xed\xda\x01\"U\n" +
	"\x14RspChatSystemHistory\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.galaxy.protocol.PChatMsgR\bmessages:\x06\xa8\xac\x1d\xee\xda\x01\"O\n" +
	"\x10NotifyChatSystem\x123\n" +
	"\amessage\x18\x01 \x01(\v2\x19.galaxy.protocol.PChatMsgR\amessage:\x06\xa8\xac\x1d\xef\xda\x01\"Y\n" +
	"\x12ReqChatSendChannel\x12!\n" +
	"\fchannel_type\x18\x01 \x01(\x05R\vchannelType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent:\x06\xa8\xac\x1d\xf4\xda\x01\"\x1c\n" +
	"\x12RspChatSendChannel:\x06\xa8\xac\x1d\xf5\xda\x01\"\xb2\x01\n" +
	"\x11NotifyChatChannel\x12!\n" +
	"\fchannel_type\x18\x01 \x01(\x05R\vchannelType\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\x03R\tchannelId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp:\x06\xa8\xac\x1d\xf6\xda\x01\"w\n" +
	"\x15ReqChatChannelHistory\x12!\n" +
	"\fchannel_type\x18\x01 \x01(\x05R\vchannelType\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\x03R\tchannelId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count:\x06\xa8\xac\x1d\xf7\xda\x01\"V\n" +
	"\x15RspChatChannelHistory\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.galaxy.protocol.PChatMsgR\bmessages:\x06\xa8\xac\x1d\xf8\xda\x01B\tZ\a./pb;pbb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_chat_proto_goTypes = []any{
	(*PChatMsg)(nil),              // 0: galaxy.protocol.PChatMsg
	(*ReqChatInit)(nil),           // 1: galaxy.protocol.ReqChatInit
	(*RspChatInit)(nil),           // 2: galaxy.protocol.RspChatInit
	(*ReqChatSendPrivate)(nil),    // 3: galaxy.protocol.ReqChatSendPrivate
	(*RspChatSendPrivate)(nil),    // 4: galaxy.protocol.RspChatSendPrivate
	(*ReqChatPrivateHistory)(nil), // 5: galaxy.protocol.ReqChatPrivateHistory
	(*RspChatPrivateHistory)(nil), // 6: galaxy.protocol.RspChatPrivateHistory
	(*NotifyChatPrivate)(nil),     // 7: galaxy.protocol.NotifyChatPrivate
	(*ReqChatSystemHistory)(nil),  // 8: galaxy.protocol.ReqChatSystemHistory
	(*RspChatSystemHistory)(nil),  // 9: galaxy.protocol.RspChatSystemHistory
	(*NotifyChatSystem)(nil),      // 10: galaxy.protocol.NotifyChatSystem
	(*ReqChatSendChannel)(nil),    // 11: galaxy.protocol.ReqChatSendChannel
	(*RspChatSendChannel)(nil),    // 12: galaxy.protocol.RspChatSendChannel
	(*NotifyChatChannel)(nil),     // 13: galaxy.protocol.NotifyChatChannel
	(*ReqChatChannelHistory)(nil), // 14: galaxy.protocol.ReqChatChannelHistory
	(*RspChatChannelHistory)(nil), // 15: galaxy.protocol.RspChatChannelHistory
	(*PRolePublic)(nil),           // 16: galaxy.protocol.PRolePublic
}
var file_chat_proto_depIdxs = []int32{
	16, // 0: galaxy.protocol.PChatMsg.sender:type_name -> galaxy.protocol.PRolePublic
	0,  // 1: galaxy.protocol.RspChatInit.world_messages:type_name -> galaxy.protocol.PChatMsg
	0,  // 2: galaxy.protocol.RspChatInit.system_messages:type_name -> galaxy.protocol.PChatMsg
	0,  // 3: galaxy.protocol.RspChatPrivateHistory.messages:type_name -> galaxy.protocol.PChatMsg
	0,  // 4: galaxy.protocol.NotifyChatPrivate.message:type_name -> galaxy.protocol.PChatMsg
	0,  // 5: galaxy.protocol.RspChatSystemHistory.messages:type_name -> galaxy.protocol.PChatMsg
	0,  // 6: galaxy.protocol.NotifyChatSystem.message:type_name -> galaxy.protocol.PChatMsg
	0,  // 7: galaxy.protocol.RspChatChannelHistory.messages:type_name -> galaxy.protocol.PChatMsg
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	file_msg_options_proto_init()
	file_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
