// ID: 23001~23099

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.0
// source: flower.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlowerState int32

const (
	FlowerState_FLOWER_UNLOCKED   FlowerState = 0
	FlowerState_FLOWER_BREEDING   FlowerState = 1
	FlowerState_FLOWER_BREED_DONE FlowerState = 2
	FlowerState_FLOWER_HARVESTED  FlowerState = 3
)

// Enum value maps for FlowerState.
var (
	FlowerState_name = map[int32]string{
		0: "FLOWER_UNLOCKED",
		1: "FLOWER_BREEDING",
		2: "FLOWER_BREED_DONE",
		3: "FLOWER_HARVESTED",
	}
	FlowerState_value = map[string]int32{
		"FLOWER_UNLOCKED":   0,
		"FLOWER_BREEDING":   1,
		"FLOWER_BREED_DONE": 2,
		"FLOWER_HARVESTED":  3,
	}
)

func (x FlowerState) Enum() *FlowerState {
	p := new(FlowerState)
	*p = x
	return p
}

func (x FlowerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowerState) Descriptor() protoreflect.EnumDescriptor {
	return file_flower_proto_enumTypes[0].Descriptor()
}

func (FlowerState) Type() protoreflect.EnumType {
	return &file_flower_proto_enumTypes[0]
}

func (x FlowerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowerState.Descriptor instead.
func (FlowerState) EnumDescriptor() ([]byte, []int) {
	return file_flower_proto_rawDescGZIP(), []int{0}
}

type PFlowerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlowerId  int32       `protobuf:"varint,1,opt,name=flower_id,json=flowerId,proto3" json:"flower_id"`
	State     FlowerState `protobuf:"varint,2,opt,name=state,proto3,enum=galaxy.protocol.FlowerState" json:"state"`
	StateTime int64       `protobuf:"varint,3,opt,name=state_time,json=stateTime,proto3" json:"state_time"`
}

func (x *PFlowerInfo) Reset() {
	*x = PFlowerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flower_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PFlowerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PFlowerInfo) ProtoMessage() {}

func (x *PFlowerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_flower_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PFlowerInfo.ProtoReflect.Descriptor instead.
func (*PFlowerInfo) Descriptor() ([]byte, []int) {
	return file_flower_proto_rawDescGZIP(), []int{0}
}

func (x *PFlowerInfo) GetFlowerId() int32 {
	if x != nil {
		return x.FlowerId
	}
	return 0
}

func (x *PFlowerInfo) GetState() FlowerState {
	if x != nil {
		return x.State
	}
	return FlowerState_FLOWER_UNLOCKED
}

func (x *PFlowerInfo) GetStateTime() int64 {
	if x != nil {
		return x.StateTime
	}
	return 0
}

type ReqFlowerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqFlowerInfo) Reset() {
	*x = ReqFlowerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flower_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqFlowerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqFlowerInfo) ProtoMessage() {}

func (x *ReqFlowerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_flower_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqFlowerInfo.ProtoReflect.Descriptor instead.
func (*ReqFlowerInfo) Descriptor() ([]byte, []int) {
	return file_flower_proto_rawDescGZIP(), []int{1}
}

type RspFlowerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flowers []*PFlowerInfo `protobuf:"bytes,1,rep,name=flowers,proto3" json:"flowers"`
}

func (x *RspFlowerInfo) Reset() {
	*x = RspFlowerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flower_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspFlowerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspFlowerInfo) ProtoMessage() {}

func (x *RspFlowerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_flower_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspFlowerInfo.ProtoReflect.Descriptor instead.
func (*RspFlowerInfo) Descriptor() ([]byte, []int) {
	return file_flower_proto_rawDescGZIP(), []int{2}
}

func (x *RspFlowerInfo) GetFlowers() []*PFlowerInfo {
	if x != nil {
		return x.Flowers
	}
	return nil
}

type ReqStartBreed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlowerId int32 `protobuf:"varint,1,opt,name=flower_id,json=flowerId,proto3" json:"flower_id"`
}

func (x *ReqStartBreed) Reset() {
	*x = ReqStartBreed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flower_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStartBreed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStartBreed) ProtoMessage() {}

func (x *ReqStartBreed) ProtoReflect() protoreflect.Message {
	mi := &file_flower_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStartBreed.ProtoReflect.Descriptor instead.
func (*ReqStartBreed) Descriptor() ([]byte, []int) {
	return file_flower_proto_rawDescGZIP(), []int{3}
}

func (x *ReqStartBreed) GetFlowerId() int32 {
	if x != nil {
		return x.FlowerId
	}
	return 0
}

type RspStartBreed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flower *PFlowerInfo `protobuf:"bytes,1,opt,name=flower,proto3" json:"flower"`
}

func (x *RspStartBreed) Reset() {
	*x = RspStartBreed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flower_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspStartBreed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspStartBreed) ProtoMessage() {}

func (x *RspStartBreed) ProtoReflect() protoreflect.Message {
	mi := &file_flower_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspStartBreed.ProtoReflect.Descriptor instead.
func (*RspStartBreed) Descriptor() ([]byte, []int) {
	return file_flower_proto_rawDescGZIP(), []int{4}
}

func (x *RspStartBreed) GetFlower() *PFlowerInfo {
	if x != nil {
		return x.Flower
	}
	return nil
}

type ReqFinishBreed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlowerId int32 `protobuf:"varint,1,opt,name=flower_id,json=flowerId,proto3" json:"flower_id"`
}

func (x *ReqFinishBreed) Reset() {
	*x = ReqFinishBreed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flower_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqFinishBreed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqFinishBreed) ProtoMessage() {}

func (x *ReqFinishBreed) ProtoReflect() protoreflect.Message {
	mi := &file_flower_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqFinishBreed.ProtoReflect.Descriptor instead.
func (*ReqFinishBreed) Descriptor() ([]byte, []int) {
	return file_flower_proto_rawDescGZIP(), []int{5}
}

func (x *ReqFinishBreed) GetFlowerId() int32 {
	if x != nil {
		return x.FlowerId
	}
	return 0
}

type RspFinishBreed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flower *PFlowerInfo `protobuf:"bytes,1,opt,name=flower,proto3" json:"flower"`
}

func (x *RspFinishBreed) Reset() {
	*x = RspFinishBreed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flower_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspFinishBreed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspFinishBreed) ProtoMessage() {}

func (x *RspFinishBreed) ProtoReflect() protoreflect.Message {
	mi := &file_flower_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspFinishBreed.ProtoReflect.Descriptor instead.
func (*RspFinishBreed) Descriptor() ([]byte, []int) {
	return file_flower_proto_rawDescGZIP(), []int{6}
}

func (x *RspFinishBreed) GetFlower() *PFlowerInfo {
	if x != nil {
		return x.Flower
	}
	return nil
}

var File_flower_proto protoreflect.FileDescriptor

var file_flower_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a,
	0x11, 0x6d, 0x73, 0x67, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x0b, 0x50, 0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x12, 0x32,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x17, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xd9, 0xb3, 0x01, 0x22, 0x4f, 0x0a, 0x0d, 0x52, 0x73,
	0x70, 0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x36, 0x0a, 0x07, 0x66,
	0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50,
	0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x77,
	0x65, 0x72, 0x73, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xda, 0xb3, 0x01, 0x22, 0x34, 0x0a, 0x0d, 0x52,
	0x65, 0x71, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x72, 0x65, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xdb, 0xb3,
	0x01, 0x22, 0x4d, 0x0a, 0x0d, 0x52, 0x73, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x72, 0x65,
	0x65, 0x64, 0x12, 0x34, 0x0a, 0x06, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x06, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xdc, 0xb3, 0x01,
	0x22, 0x35, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x42, 0x72, 0x65,
	0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x3a,
	0x06, 0xa8, 0xac, 0x1d, 0xdd, 0xb3, 0x01, 0x22, 0x4e, 0x0a, 0x0e, 0x52, 0x73, 0x70, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x42, 0x72, 0x65, 0x65, 0x64, 0x12, 0x34, 0x0a, 0x06, 0x66, 0x6c, 0x6f,
	0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6c, 0x61,
	0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x46, 0x6c, 0x6f,
	0x77, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x3a,
	0x06, 0xa8, 0xac, 0x1d, 0xde, 0xb3, 0x01, 0x2a, 0x64, 0x0a, 0x0b, 0x46, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x46, 0x4c, 0x4f, 0x57, 0x45, 0x52,
	0x5f, 0x55, 0x4e, 0x4c, 0x4f, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x46,
	0x4c, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x42, 0x52, 0x45, 0x45, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x12, 0x15, 0x0a, 0x11, 0x46, 0x4c, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x42, 0x52, 0x45, 0x45, 0x44,
	0x5f, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x46, 0x4c, 0x4f, 0x57, 0x45,
	0x52, 0x5f, 0x48, 0x41, 0x52, 0x56, 0x45, 0x53, 0x54, 0x45, 0x44, 0x10, 0x03, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flower_proto_rawDescOnce sync.Once
	file_flower_proto_rawDescData = file_flower_proto_rawDesc
)

func file_flower_proto_rawDescGZIP() []byte {
	file_flower_proto_rawDescOnce.Do(func() {
		file_flower_proto_rawDescData = protoimpl.X.CompressGZIP(file_flower_proto_rawDescData)
	})
	return file_flower_proto_rawDescData
}

var file_flower_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_flower_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_flower_proto_goTypes = []interface{}{
	(FlowerState)(0),       // 0: galaxy.protocol.FlowerState
	(*PFlowerInfo)(nil),    // 1: galaxy.protocol.PFlowerInfo
	(*ReqFlowerInfo)(nil),  // 2: galaxy.protocol.ReqFlowerInfo
	(*RspFlowerInfo)(nil),  // 3: galaxy.protocol.RspFlowerInfo
	(*ReqStartBreed)(nil),  // 4: galaxy.protocol.ReqStartBreed
	(*RspStartBreed)(nil),  // 5: galaxy.protocol.RspStartBreed
	(*ReqFinishBreed)(nil), // 6: galaxy.protocol.ReqFinishBreed
	(*RspFinishBreed)(nil), // 7: galaxy.protocol.RspFinishBreed
}
var file_flower_proto_depIdxs = []int32{
	0, // 0: galaxy.protocol.PFlowerInfo.state:type_name -> galaxy.protocol.FlowerState
	1, // 1: galaxy.protocol.RspFlowerInfo.flowers:type_name -> galaxy.protocol.PFlowerInfo
	1, // 2: galaxy.protocol.RspStartBreed.flower:type_name -> galaxy.protocol.PFlowerInfo
	1, // 3: galaxy.protocol.RspFinishBreed.flower:type_name -> galaxy.protocol.PFlowerInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_flower_proto_init() }
func file_flower_proto_init() {
	if File_flower_proto != nil {
		return
	}
	file_msg_options_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_flower_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PFlowerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flower_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqFlowerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flower_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspFlowerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flower_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStartBreed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flower_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspStartBreed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flower_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqFinishBreed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flower_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspFinishBreed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flower_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flower_proto_goTypes,
		DependencyIndexes: file_flower_proto_depIdxs,
		EnumInfos:         file_flower_proto_enumTypes,
		MessageInfos:      file_flower_proto_msgTypes,
	}.Build()
	File_flower_proto = out.File
	file_flower_proto_rawDesc = nil
	file_flower_proto_goTypes = nil
	file_flower_proto_depIdxs = nil
}
