// ID: 27001~27099

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.0
// source: friend.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 搜索玩家 (27001)
type ReqSearchPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
}

func (x *ReqSearchPlayer) Reset() {
	*x = ReqSearchPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSearchPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSearchPlayer) ProtoMessage() {}

func (x *ReqSearchPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSearchPlayer.ProtoReflect.Descriptor instead.
func (*ReqSearchPlayer) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{0}
}

func (x *ReqSearchPlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RspSearchPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []*PPlayerInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players"`
}

func (x *RspSearchPlayer) Reset() {
	*x = RspSearchPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspSearchPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspSearchPlayer) ProtoMessage() {}

func (x *RspSearchPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspSearchPlayer.ProtoReflect.Descriptor instead.
func (*RspSearchPlayer) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{1}
}

func (x *RspSearchPlayer) GetPlayers() []*PPlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type PPlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerInfo *PRolePublic `protobuf:"bytes,1,opt,name=player_info,json=playerInfo,proto3" json:"player_info"`
	Relation   int32        `protobuf:"varint,2,opt,name=relation,proto3" json:"relation"` // 0=自己 1=可申请 2=已申请 3=已是好友
}

func (x *PPlayerInfo) Reset() {
	*x = PPlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PPlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPlayerInfo) ProtoMessage() {}

func (x *PPlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPlayerInfo.ProtoReflect.Descriptor instead.
func (*PPlayerInfo) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{2}
}

func (x *PPlayerInfo) GetPlayerInfo() *PRolePublic {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

func (x *PPlayerInfo) GetRelation() int32 {
	if x != nil {
		return x.Relation
	}
	return 0
}

// 发送申请 (27003)
type ReqSendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetIds []int64 `protobuf:"varint,1,rep,packed,name=target_ids,json=targetIds,proto3" json:"target_ids"`
}

func (x *ReqSendRequest) Reset() {
	*x = ReqSendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendRequest) ProtoMessage() {}

func (x *ReqSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendRequest.ProtoReflect.Descriptor instead.
func (*ReqSendRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{3}
}

func (x *ReqSendRequest) GetTargetIds() []int64 {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

type RspSendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Friends []*PFriendInfo `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends"`
}

func (x *RspSendRequest) Reset() {
	*x = RspSendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspSendRequest) ProtoMessage() {}

func (x *RspSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspSendRequest.ProtoReflect.Descriptor instead.
func (*RspSendRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{4}
}

func (x *RspSendRequest) GetFriends() []*PFriendInfo {
	if x != nil {
		return x.Friends
	}
	return nil
}

// 同意申请 (27005)
type ReqAcceptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromIds []int64 `protobuf:"varint,1,rep,packed,name=from_ids,json=fromIds,proto3" json:"from_ids"`
}

func (x *ReqAcceptRequest) Reset() {
	*x = ReqAcceptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAcceptRequest) ProtoMessage() {}

func (x *ReqAcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAcceptRequest.ProtoReflect.Descriptor instead.
func (*ReqAcceptRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{5}
}

func (x *ReqAcceptRequest) GetFromIds() []int64 {
	if x != nil {
		return x.FromIds
	}
	return nil
}

type RspAcceptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Friends []*PFriendInfo `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends"`
}

func (x *RspAcceptRequest) Reset() {
	*x = RspAcceptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspAcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspAcceptRequest) ProtoMessage() {}

func (x *RspAcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspAcceptRequest.ProtoReflect.Descriptor instead.
func (*RspAcceptRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{6}
}

func (x *RspAcceptRequest) GetFriends() []*PFriendInfo {
	if x != nil {
		return x.Friends
	}
	return nil
}

// 拒绝申请 (27007)
type ReqRejectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromIds []int64 `protobuf:"varint,1,rep,packed,name=from_ids,json=fromIds,proto3" json:"from_ids"`
}

func (x *ReqRejectRequest) Reset() {
	*x = ReqRejectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqRejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRejectRequest) ProtoMessage() {}

func (x *ReqRejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRejectRequest.ProtoReflect.Descriptor instead.
func (*ReqRejectRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{7}
}

func (x *ReqRejectRequest) GetFromIds() []int64 {
	if x != nil {
		return x.FromIds
	}
	return nil
}

type RspRejectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RspRejectRequest) Reset() {
	*x = RspRejectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspRejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspRejectRequest) ProtoMessage() {}

func (x *RspRejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspRejectRequest.ProtoReflect.Descriptor instead.
func (*RspRejectRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{8}
}

// 好友列表 (27009)
type ReqFriendList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqFriendList) Reset() {
	*x = ReqFriendList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqFriendList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqFriendList) ProtoMessage() {}

func (x *ReqFriendList) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqFriendList.ProtoReflect.Descriptor instead.
func (*ReqFriendList) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{9}
}

type RspFriendList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total   int32          `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Limit   int32          `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
	Friends []*PFriendInfo `protobuf:"bytes,3,rep,name=friends,proto3" json:"friends"`
}

func (x *RspFriendList) Reset() {
	*x = RspFriendList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspFriendList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspFriendList) ProtoMessage() {}

func (x *RspFriendList) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspFriendList.ProtoReflect.Descriptor instead.
func (*RspFriendList) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{10}
}

func (x *RspFriendList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RspFriendList) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RspFriendList) GetFriends() []*PFriendInfo {
	if x != nil {
		return x.Friends
	}
	return nil
}

type PFriendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerInfo  *PRolePublic `protobuf:"bytes,1,opt,name=player_info,json=playerInfo,proto3" json:"player_info"`
	FriendSince int64        `protobuf:"varint,2,opt,name=friend_since,json=friendSince,proto3" json:"friend_since"`
}

func (x *PFriendInfo) Reset() {
	*x = PFriendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PFriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PFriendInfo) ProtoMessage() {}

func (x *PFriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PFriendInfo.ProtoReflect.Descriptor instead.
func (*PFriendInfo) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{11}
}

func (x *PFriendInfo) GetPlayerInfo() *PRolePublic {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

func (x *PFriendInfo) GetFriendSince() int64 {
	if x != nil {
		return x.FriendSince
	}
	return 0
}

// 申请列表 (27011)
type ReqApplyList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqApplyList) Reset() {
	*x = ReqApplyList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqApplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqApplyList) ProtoMessage() {}

func (x *ReqApplyList) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqApplyList.ProtoReflect.Descriptor instead.
func (*ReqApplyList) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{12}
}

type RspApplyList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Incoming []*PApplyInfo `protobuf:"bytes,1,rep,name=incoming,proto3" json:"incoming"`
	Outgoing []*PApplyInfo `protobuf:"bytes,2,rep,name=outgoing,proto3" json:"outgoing"`
}

func (x *RspApplyList) Reset() {
	*x = RspApplyList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspApplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspApplyList) ProtoMessage() {}

func (x *RspApplyList) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspApplyList.ProtoReflect.Descriptor instead.
func (*RspApplyList) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{13}
}

func (x *RspApplyList) GetIncoming() []*PApplyInfo {
	if x != nil {
		return x.Incoming
	}
	return nil
}

func (x *RspApplyList) GetOutgoing() []*PApplyInfo {
	if x != nil {
		return x.Outgoing
	}
	return nil
}

type PApplyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerInfo *PRolePublic `protobuf:"bytes,1,opt,name=player_info,json=playerInfo,proto3" json:"player_info"`
	ApplyAt    int64        `protobuf:"varint,2,opt,name=apply_at,json=applyAt,proto3" json:"apply_at"`
	Status     int32        `protobuf:"varint,3,opt,name=status,proto3" json:"status"` // 0=待处理 1=已同意 2=已拒绝
}

func (x *PApplyInfo) Reset() {
	*x = PApplyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PApplyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PApplyInfo) ProtoMessage() {}

func (x *PApplyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PApplyInfo.ProtoReflect.Descriptor instead.
func (*PApplyInfo) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{14}
}

func (x *PApplyInfo) GetPlayerInfo() *PRolePublic {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

func (x *PApplyInfo) GetApplyAt() int64 {
	if x != nil {
		return x.ApplyAt
	}
	return 0
}

func (x *PApplyInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 删除好友 (27013)
type ReqRemoveFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetId int64 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id"`
}

func (x *ReqRemoveFriend) Reset() {
	*x = ReqRemoveFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqRemoveFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRemoveFriend) ProtoMessage() {}

func (x *ReqRemoveFriend) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRemoveFriend.ProtoReflect.Descriptor instead.
func (*ReqRemoveFriend) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{15}
}

func (x *ReqRemoveFriend) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type RspRemoveFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RspRemoveFriend) Reset() {
	*x = RspRemoveFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspRemoveFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspRemoveFriend) ProtoMessage() {}

func (x *RspRemoveFriend) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspRemoveFriend.ProtoReflect.Descriptor instead.
func (*RspRemoveFriend) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{16}
}

// 通知：收到新的好友申请 (27015)
type NotifyNewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplyInfo *PApplyInfo `protobuf:"bytes,1,opt,name=apply_info,json=applyInfo,proto3" json:"apply_info"`
}

func (x *NotifyNewRequest) Reset() {
	*x = NotifyNewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyNewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewRequest) ProtoMessage() {}

func (x *NotifyNewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewRequest.ProtoReflect.Descriptor instead.
func (*NotifyNewRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{17}
}

func (x *NotifyNewRequest) GetApplyInfo() *PApplyInfo {
	if x != nil {
		return x.ApplyInfo
	}
	return nil
}

// 通知：新增好友 (27016)
type NotifyNewFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendInfo *PFriendInfo `protobuf:"bytes,1,opt,name=friend_info,json=friendInfo,proto3" json:"friend_info"`
}

func (x *NotifyNewFriend) Reset() {
	*x = NotifyNewFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyNewFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewFriend) ProtoMessage() {}

func (x *NotifyNewFriend) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewFriend.ProtoReflect.Descriptor instead.
func (*NotifyNewFriend) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{18}
}

func (x *NotifyNewFriend) GetFriendInfo() *PFriendInfo {
	if x != nil {
		return x.FriendInfo
	}
	return nil
}

var File_friend_proto protoreflect.FileDescriptor

var file_friend_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a,
	0x11, 0x6d, 0x73, 0x67, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d,
	0x0a, 0x0f, 0x52, 0x65, 0x71, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xf9, 0xd2, 0x01, 0x22, 0x51, 0x0a,
	0x0f, 0x52, 0x73, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x36, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xfa, 0xd2, 0x01,
	0x22, 0x68, 0x0a, 0x0b, 0x50, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x3d, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x0e, 0x52, 0x65,
	0x71, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x73, 0x3a, 0x06, 0xa8, 0xac, 0x1d,
	0xfb, 0xd2, 0x01, 0x22, 0x50, 0x0a, 0x0e, 0x52, 0x73, 0x70, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x3a, 0x06, 0xa8,
	0xac, 0x1d, 0xfc, 0xd2, 0x01, 0x22, 0x35, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x66, 0x72, 0x6f,
	0x6d, 0x49, 0x64, 0x73, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xfd, 0xd2, 0x01, 0x22, 0x52, 0x0a, 0x10,
	0x52, 0x73, 0x70, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x36, 0x0a, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xfe, 0xd2, 0x01,
	0x22, 0x35, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x73, 0x3a,
	0x06, 0xa8, 0xac, 0x1d, 0xff, 0xd2, 0x01, 0x22, 0x1a, 0x0a, 0x10, 0x52, 0x73, 0x70, 0x52, 0x65,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x3a, 0x06, 0xa8, 0xac, 0x1d,
	0x80, 0xd3, 0x01, 0x22, 0x17, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0x81, 0xd3, 0x01, 0x22, 0x7b, 0x0a, 0x0d,
	0x52, 0x73, 0x70, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6c,
	0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x73, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0x82, 0xd3, 0x01, 0x22, 0x6f, 0x0a, 0x0b, 0x50, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x50, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x52, 0x0a, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x5f, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x53, 0x69, 0x6e, 0x63, 0x65, 0x22, 0x16, 0x0a, 0x0c, 0x52, 0x65,
	0x71, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0x83,
	0xd3, 0x01, 0x22, 0x88, 0x01, 0x0a, 0x0c, 0x52, 0x73, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x08, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x08, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x37, 0x0a, 0x08,
	0x6f, 0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x50, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x6f, 0x75, 0x74,
	0x67, 0x6f, 0x69, 0x6e, 0x67, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0x84, 0xd3, 0x01, 0x22, 0x7e, 0x0a,
	0x0a, 0x50, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x0b, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x50, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x52, 0x0a,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70,
	0x70, 0x6c, 0x79, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x70,
	0x70, 0x6c, 0x79, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x36, 0x0a,
	0x0f, 0x52, 0x65, 0x71, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x3a, 0x06, 0xa8,
	0xac, 0x1d, 0x85, 0xd3, 0x01, 0x22, 0x19, 0x0a, 0x0f, 0x52, 0x73, 0x70, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0x86, 0xd3, 0x01,
	0x22, 0x56, 0x0a, 0x10, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x3a, 0x06, 0xa8, 0xac, 0x1d, 0x87, 0xd3, 0x01, 0x22, 0x58, 0x0a, 0x0f, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x4e, 0x65, 0x77, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x3d, 0x0a, 0x0b, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x50, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0x88,
	0xd3, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_friend_proto_rawDescOnce sync.Once
	file_friend_proto_rawDescData = file_friend_proto_rawDesc
)

func file_friend_proto_rawDescGZIP() []byte {
	file_friend_proto_rawDescOnce.Do(func() {
		file_friend_proto_rawDescData = protoimpl.X.CompressGZIP(file_friend_proto_rawDescData)
	})
	return file_friend_proto_rawDescData
}

var file_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_friend_proto_goTypes = []interface{}{
	(*ReqSearchPlayer)(nil),  // 0: galaxy.protocol.ReqSearchPlayer
	(*RspSearchPlayer)(nil),  // 1: galaxy.protocol.RspSearchPlayer
	(*PPlayerInfo)(nil),      // 2: galaxy.protocol.PPlayerInfo
	(*ReqSendRequest)(nil),   // 3: galaxy.protocol.ReqSendRequest
	(*RspSendRequest)(nil),   // 4: galaxy.protocol.RspSendRequest
	(*ReqAcceptRequest)(nil), // 5: galaxy.protocol.ReqAcceptRequest
	(*RspAcceptRequest)(nil), // 6: galaxy.protocol.RspAcceptRequest
	(*ReqRejectRequest)(nil), // 7: galaxy.protocol.ReqRejectRequest
	(*RspRejectRequest)(nil), // 8: galaxy.protocol.RspRejectRequest
	(*ReqFriendList)(nil),    // 9: galaxy.protocol.ReqFriendList
	(*RspFriendList)(nil),    // 10: galaxy.protocol.RspFriendList
	(*PFriendInfo)(nil),      // 11: galaxy.protocol.PFriendInfo
	(*ReqApplyList)(nil),     // 12: galaxy.protocol.ReqApplyList
	(*RspApplyList)(nil),     // 13: galaxy.protocol.RspApplyList
	(*PApplyInfo)(nil),       // 14: galaxy.protocol.PApplyInfo
	(*ReqRemoveFriend)(nil),  // 15: galaxy.protocol.ReqRemoveFriend
	(*RspRemoveFriend)(nil),  // 16: galaxy.protocol.RspRemoveFriend
	(*NotifyNewRequest)(nil), // 17: galaxy.protocol.NotifyNewRequest
	(*NotifyNewFriend)(nil),  // 18: galaxy.protocol.NotifyNewFriend
	(*PRolePublic)(nil),      // 19: galaxy.protocol.PRolePublic
}
var file_friend_proto_depIdxs = []int32{
	2,  // 0: galaxy.protocol.RspSearchPlayer.players:type_name -> galaxy.protocol.PPlayerInfo
	19, // 1: galaxy.protocol.PPlayerInfo.player_info:type_name -> galaxy.protocol.PRolePublic
	11, // 2: galaxy.protocol.RspSendRequest.friends:type_name -> galaxy.protocol.PFriendInfo
	11, // 3: galaxy.protocol.RspAcceptRequest.friends:type_name -> galaxy.protocol.PFriendInfo
	11, // 4: galaxy.protocol.RspFriendList.friends:type_name -> galaxy.protocol.PFriendInfo
	19, // 5: galaxy.protocol.PFriendInfo.player_info:type_name -> galaxy.protocol.PRolePublic
	14, // 6: galaxy.protocol.RspApplyList.incoming:type_name -> galaxy.protocol.PApplyInfo
	14, // 7: galaxy.protocol.RspApplyList.outgoing:type_name -> galaxy.protocol.PApplyInfo
	19, // 8: galaxy.protocol.PApplyInfo.player_info:type_name -> galaxy.protocol.PRolePublic
	14, // 9: galaxy.protocol.NotifyNewRequest.apply_info:type_name -> galaxy.protocol.PApplyInfo
	11, // 10: galaxy.protocol.NotifyNewFriend.friend_info:type_name -> galaxy.protocol.PFriendInfo
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_friend_proto_init() }
func file_friend_proto_init() {
	if File_friend_proto != nil {
		return
	}
	file_msg_options_proto_init()
	file_role_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_friend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSearchPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspSearchPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PPlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspSendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAcceptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspAcceptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqRejectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspRejectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqFriendList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspFriendList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PFriendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqApplyList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspApplyList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PApplyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqRemoveFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspRemoveFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyNewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyNewFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_friend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_friend_proto_goTypes,
		DependencyIndexes: file_friend_proto_depIdxs,
		MessageInfos:      file_friend_proto_msgTypes,
	}.Build()
	File_friend_proto = out.File
	file_friend_proto_rawDesc = nil
	file_friend_proto_goTypes = nil
	file_friend_proto_depIdxs = nil
}
