// === 频道 Actor 内部消息（服务器内部使用，无 msg_id） ===

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.3
// source: gchat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelRegisterMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id"`
	Pid           *ActorPid              `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid"`
	ChannelType   int32                  `protobuf:"varint,3,opt,name=channel_type,json=channelType,proto3" json:"channel_type"`
	ChannelId     int64                  `protobuf:"varint,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelRegisterMsg) Reset() {
	*x = ChannelRegisterMsg{}
	mi := &file_gchat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRegisterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRegisterMsg) ProtoMessage() {}

func (x *ChannelRegisterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gchat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRegisterMsg.ProtoReflect.Descriptor instead.
func (*ChannelRegisterMsg) Descriptor() ([]byte, []int) {
	return file_gchat_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelRegisterMsg) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ChannelRegisterMsg) GetPid() *ActorPid {
	if x != nil {
		return x.Pid
	}
	return nil
}

func (x *ChannelRegisterMsg) GetChannelType() int32 {
	if x != nil {
		return x.ChannelType
	}
	return 0
}

func (x *ChannelRegisterMsg) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type ChannelUnregisterMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id"`
	ChannelType   int32                  `protobuf:"varint,2,opt,name=channel_type,json=channelType,proto3" json:"channel_type"`
	ChannelId     int64                  `protobuf:"varint,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelUnregisterMsg) Reset() {
	*x = ChannelUnregisterMsg{}
	mi := &file_gchat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelUnregisterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelUnregisterMsg) ProtoMessage() {}

func (x *ChannelUnregisterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gchat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelUnregisterMsg.ProtoReflect.Descriptor instead.
func (*ChannelUnregisterMsg) Descriptor() ([]byte, []int) {
	return file_gchat_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelUnregisterMsg) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ChannelUnregisterMsg) GetChannelType() int32 {
	if x != nil {
		return x.ChannelType
	}
	return 0
}

func (x *ChannelUnregisterMsg) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

// 发送频道消息（Actor 内部请求）
type ReqChannelSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelType   int32                  `protobuf:"varint,1,opt,name=channel_type,json=channelType,proto3" json:"channel_type"`
	ChannelId     int64                  `protobuf:"varint,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id"`
	SenderId      int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqChannelSend) Reset() {
	*x = ReqChannelSend{}
	mi := &file_gchat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqChannelSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChannelSend) ProtoMessage() {}

func (x *ReqChannelSend) ProtoReflect() protoreflect.Message {
	mi := &file_gchat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChannelSend.ProtoReflect.Descriptor instead.
func (*ReqChannelSend) Descriptor() ([]byte, []int) {
	return file_gchat_proto_rawDescGZIP(), []int{2}
}

func (x *ReqChannelSend) GetChannelType() int32 {
	if x != nil {
		return x.ChannelType
	}
	return 0
}

func (x *ReqChannelSend) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ReqChannelSend) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ReqChannelSend) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_gchat_proto protoreflect.FileDescriptor

const file_gchat_proto_rawDesc = "" +
	"\n" +
	"\vgchat.proto\x12\x0fgalaxy.protocol\x1a\fgactor.proto\"\x9c\x01\n" +
	"\x12ChannelRegisterMsg\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12+\n" +
	"\x03pid\x18\x02 \x01(\v2\x19.galaxy.protocol.ActorPidR\x03pid\x12!\n" +
	"\fchannel_type\x18\x03 \x01(\x05R\vchannelType\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\x03R\tchannelId\"q\n" +
	"\x14ChannelUnregisterMsg\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12!\n" +
	"\fchannel_type\x18\x02 \x01(\x05R\vchannelType\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\x03R\tchannelId\"\x89\x01\n" +
	"\x0eReqChannelSend\x12!\n" +
	"\fchannel_type\x18\x01 \x01(\x05R\vchannelType\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\x03R\tchannelId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontentB\tZ\a./pb;pbb\x06proto3"

var (
	file_gchat_proto_rawDescOnce sync.Once
	file_gchat_proto_rawDescData []byte
)

func file_gchat_proto_rawDescGZIP() []byte {
	file_gchat_proto_rawDescOnce.Do(func() {
		file_gchat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gchat_proto_rawDesc), len(file_gchat_proto_rawDesc)))
	})
	return file_gchat_proto_rawDescData
}

var file_gchat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gchat_proto_goTypes = []any{
	(*ChannelRegisterMsg)(nil),   // 0: galaxy.protocol.ChannelRegisterMsg
	(*ChannelUnregisterMsg)(nil), // 1: galaxy.protocol.ChannelUnregisterMsg
	(*ReqChannelSend)(nil),       // 2: galaxy.protocol.ReqChannelSend
	(*ActorPid)(nil),             // 3: galaxy.protocol.ActorPid
}
var file_gchat_proto_depIdxs = []int32{
	3, // 0: galaxy.protocol.ChannelRegisterMsg.pid:type_name -> galaxy.protocol.ActorPid
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gchat_proto_init() }
func file_gchat_proto_init() {
	if File_gchat_proto != nil {
		return
	}
	file_gactor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gchat_proto_rawDesc), len(file_gchat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gchat_proto_goTypes,
		DependencyIndexes: file_gchat_proto_depIdxs,
		MessageInfos:      file_gchat_proto_msgTypes,
	}.Build()
	File_gchat_proto = out.File
	file_gchat_proto_goTypes = nil
	file_gchat_proto_depIdxs = nil
}
