// ID: 30001~30099

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.0
// source: mail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqMailList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqMailList) Reset() {
	*x = ReqMailList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMailList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMailList) ProtoMessage() {}

func (x *ReqMailList) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMailList.ProtoReflect.Descriptor instead.
func (*ReqMailList) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{0}
}

type RspMailList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mails []*PMailDetail `protobuf:"bytes,1,rep,name=mails,proto3" json:"mails"`
}

func (x *RspMailList) Reset() {
	*x = RspMailList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspMailList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMailList) ProtoMessage() {}

func (x *RspMailList) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMailList.ProtoReflect.Descriptor instead.
func (*RspMailList) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{1}
}

func (x *RspMailList) GetMails() []*PMailDetail {
	if x != nil {
		return x.Mails
	}
	return nil
}

type ReqMailRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailId int64 `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id"`
}

func (x *ReqMailRead) Reset() {
	*x = ReqMailRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMailRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMailRead) ProtoMessage() {}

func (x *ReqMailRead) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMailRead.ProtoReflect.Descriptor instead.
func (*ReqMailRead) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{2}
}

func (x *ReqMailRead) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type RspMailDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail *PMailDetail `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail"`
}

func (x *RspMailDetail) Reset() {
	*x = RspMailDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspMailDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMailDetail) ProtoMessage() {}

func (x *RspMailDetail) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMailDetail.ProtoReflect.Descriptor instead.
func (*RspMailDetail) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{3}
}

func (x *RspMailDetail) GetMail() *PMailDetail {
	if x != nil {
		return x.Mail
	}
	return nil
}

type PMailDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title       string       `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Summary     string       `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary"`
	Content     string       `protobuf:"bytes,4,opt,name=content,proto3" json:"content"`
	SendAt      int64        `protobuf:"varint,5,opt,name=send_at,json=sendAt,proto3" json:"send_at"`
	ExpireAt    int64        `protobuf:"varint,6,opt,name=expire_at,json=expireAt,proto3" json:"expire_at"`
	Attachments []*PGoodInfo `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments"`
	IsRead      bool         `protobuf:"varint,8,opt,name=is_read,json=isRead,proto3" json:"is_read"`
	IsClaimed   bool         `protobuf:"varint,9,opt,name=is_claimed,json=isClaimed,proto3" json:"is_claimed"`
}

func (x *PMailDetail) Reset() {
	*x = PMailDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PMailDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PMailDetail) ProtoMessage() {}

func (x *PMailDetail) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PMailDetail.ProtoReflect.Descriptor instead.
func (*PMailDetail) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{4}
}

func (x *PMailDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PMailDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PMailDetail) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PMailDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PMailDetail) GetSendAt() int64 {
	if x != nil {
		return x.SendAt
	}
	return 0
}

func (x *PMailDetail) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *PMailDetail) GetAttachments() []*PGoodInfo {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *PMailDetail) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *PMailDetail) GetIsClaimed() bool {
	if x != nil {
		return x.IsClaimed
	}
	return false
}

type ReqMailClaim struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailId int64 `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id"`
}

func (x *ReqMailClaim) Reset() {
	*x = ReqMailClaim{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMailClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMailClaim) ProtoMessage() {}

func (x *ReqMailClaim) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMailClaim.ProtoReflect.Descriptor instead.
func (*ReqMailClaim) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{5}
}

func (x *ReqMailClaim) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type RspMailClaim struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail *PMailDetail `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail"`
}

func (x *RspMailClaim) Reset() {
	*x = RspMailClaim{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspMailClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMailClaim) ProtoMessage() {}

func (x *RspMailClaim) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMailClaim.ProtoReflect.Descriptor instead.
func (*RspMailClaim) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{6}
}

func (x *RspMailClaim) GetMail() *PMailDetail {
	if x != nil {
		return x.Mail
	}
	return nil
}

type ReqMailClaimAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqMailClaimAll) Reset() {
	*x = ReqMailClaimAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMailClaimAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMailClaimAll) ProtoMessage() {}

func (x *ReqMailClaimAll) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMailClaimAll.ProtoReflect.Descriptor instead.
func (*ReqMailClaimAll) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{7}
}

type RspMailClaimAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mails []*PMailDetail `protobuf:"bytes,1,rep,name=mails,proto3" json:"mails"`
}

func (x *RspMailClaimAll) Reset() {
	*x = RspMailClaimAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspMailClaimAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMailClaimAll) ProtoMessage() {}

func (x *RspMailClaimAll) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMailClaimAll.ProtoReflect.Descriptor instead.
func (*RspMailClaimAll) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{8}
}

func (x *RspMailClaimAll) GetMails() []*PMailDetail {
	if x != nil {
		return x.Mails
	}
	return nil
}

type ReqMailDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailId int64 `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id"`
}

func (x *ReqMailDelete) Reset() {
	*x = ReqMailDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMailDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMailDelete) ProtoMessage() {}

func (x *ReqMailDelete) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMailDelete.ProtoReflect.Descriptor instead.
func (*ReqMailDelete) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{9}
}

func (x *ReqMailDelete) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type RspMailDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail *PMailDetail `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail"`
}

func (x *RspMailDelete) Reset() {
	*x = RspMailDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspMailDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMailDelete) ProtoMessage() {}

func (x *RspMailDelete) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMailDelete.ProtoReflect.Descriptor instead.
func (*RspMailDelete) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{10}
}

func (x *RspMailDelete) GetMail() *PMailDetail {
	if x != nil {
		return x.Mail
	}
	return nil
}

type NotifyMailUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailId int64 `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id"`
}

func (x *NotifyMailUpdate) Reset() {
	*x = NotifyMailUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyMailUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyMailUpdate) ProtoMessage() {}

func (x *NotifyMailUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyMailUpdate.ProtoReflect.Descriptor instead.
func (*NotifyMailUpdate) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{11}
}

func (x *NotifyMailUpdate) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

var File_mail_proto protoreflect.FileDescriptor

var file_mail_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x61,
	0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x11, 0x6d,
	0x73, 0x67, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x09, 0x62, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x0b, 0x52,
	0x65, 0x71, 0x4d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xb1,
	0xea, 0x01, 0x22, 0x49, 0x0a, 0x0b, 0x52, 0x73, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x32, 0x0a, 0x05, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x50, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05,
	0x6d, 0x61, 0x69, 0x6c, 0x73, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xb2, 0xea, 0x01, 0x22, 0x2e, 0x0a,
	0x0b, 0x52, 0x65, 0x71, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x61, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d,
	0x61, 0x69, 0x6c, 0x49, 0x64, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xb3, 0xea, 0x01, 0x22, 0x49, 0x0a,
	0x0d, 0x52, 0x73, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x30,
	0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50,
	0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c,
	0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xb4, 0xea, 0x01, 0x22, 0x93, 0x02, 0x0a, 0x0b, 0x50, 0x4d, 0x61,
	0x69, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x50, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x61,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x22, 0x2f,
	0x0a, 0x0c, 0x52, 0x65, 0x71, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x12, 0x17,
	0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xb5, 0xea, 0x01, 0x22,
	0x48, 0x0a, 0x0c, 0x52, 0x73, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x12,
	0x30, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x50, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x6d, 0x61, 0x69,
	0x6c, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xb6, 0xea, 0x01, 0x22, 0x19, 0x0a, 0x0f, 0x52, 0x65, 0x71,
	0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x41, 0x6c, 0x6c, 0x3a, 0x06, 0xa8, 0xac,
	0x1d, 0xb7, 0xea, 0x01, 0x22, 0x4d, 0x0a, 0x0f, 0x52, 0x73, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x41, 0x6c, 0x6c, 0x12, 0x32, 0x0a, 0x05, 0x6d, 0x61, 0x69, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x3a, 0x06, 0xa8, 0xac, 0x1d,
	0xb8, 0xea, 0x01, 0x22, 0x30, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x3a, 0x06, 0xa8,
	0xac, 0x1d, 0xb9, 0xea, 0x01, 0x22, 0x49, 0x0a, 0x0d, 0x52, 0x73, 0x70, 0x4d, 0x61, 0x69, 0x6c,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xba, 0xea, 0x01,
	0x22, 0x33, 0x0a, 0x10, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4d, 0x61, 0x69, 0x6c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x3a, 0x06, 0xa8,
	0xac, 0x1d, 0xbb, 0xea, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mail_proto_rawDescOnce sync.Once
	file_mail_proto_rawDescData = file_mail_proto_rawDesc
)

func file_mail_proto_rawDescGZIP() []byte {
	file_mail_proto_rawDescOnce.Do(func() {
		file_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_mail_proto_rawDescData)
	})
	return file_mail_proto_rawDescData
}

var file_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_mail_proto_goTypes = []interface{}{
	(*ReqMailList)(nil),      // 0: galaxy.protocol.ReqMailList
	(*RspMailList)(nil),      // 1: galaxy.protocol.RspMailList
	(*ReqMailRead)(nil),      // 2: galaxy.protocol.ReqMailRead
	(*RspMailDetail)(nil),    // 3: galaxy.protocol.RspMailDetail
	(*PMailDetail)(nil),      // 4: galaxy.protocol.PMailDetail
	(*ReqMailClaim)(nil),     // 5: galaxy.protocol.ReqMailClaim
	(*RspMailClaim)(nil),     // 6: galaxy.protocol.RspMailClaim
	(*ReqMailClaimAll)(nil),  // 7: galaxy.protocol.ReqMailClaimAll
	(*RspMailClaimAll)(nil),  // 8: galaxy.protocol.RspMailClaimAll
	(*ReqMailDelete)(nil),    // 9: galaxy.protocol.ReqMailDelete
	(*RspMailDelete)(nil),    // 10: galaxy.protocol.RspMailDelete
	(*NotifyMailUpdate)(nil), // 11: galaxy.protocol.NotifyMailUpdate
	(*PGoodInfo)(nil),        // 12: galaxy.protocol.PGoodInfo
}
var file_mail_proto_depIdxs = []int32{
	4,  // 0: galaxy.protocol.RspMailList.mails:type_name -> galaxy.protocol.PMailDetail
	4,  // 1: galaxy.protocol.RspMailDetail.mail:type_name -> galaxy.protocol.PMailDetail
	12, // 2: galaxy.protocol.PMailDetail.attachments:type_name -> galaxy.protocol.PGoodInfo
	4,  // 3: galaxy.protocol.RspMailClaim.mail:type_name -> galaxy.protocol.PMailDetail
	4,  // 4: galaxy.protocol.RspMailClaimAll.mails:type_name -> galaxy.protocol.PMailDetail
	4,  // 5: galaxy.protocol.RspMailDelete.mail:type_name -> galaxy.protocol.PMailDetail
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_mail_proto_init() }
func file_mail_proto_init() {
	if File_mail_proto != nil {
		return
	}
	file_msg_options_proto_init()
	file_bag_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMailList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspMailList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMailRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspMailDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PMailDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMailClaim); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspMailClaim); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMailClaimAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspMailClaimAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMailDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspMailDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyMailUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mail_proto_goTypes,
		DependencyIndexes: file_mail_proto_depIdxs,
		MessageInfos:      file_mail_proto_msgTypes,
	}.Build()
	File_mail_proto = out.File
	file_mail_proto_rawDesc = nil
	file_mail_proto_goTypes = nil
	file_mail_proto_depIdxs = nil
}
