// ID: 30001~30099

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.3
// source: mail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqMailList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqMailList) Reset() {
	*x = ReqMailList{}
	mi := &file_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqMailList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMailList) ProtoMessage() {}

func (x *ReqMailList) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMailList.ProtoReflect.Descriptor instead.
func (*ReqMailList) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{0}
}

type RspMailList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mails         []*PMailDetail         `protobuf:"bytes,1,rep,name=mails,proto3" json:"mails"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspMailList) Reset() {
	*x = RspMailList{}
	mi := &file_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspMailList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMailList) ProtoMessage() {}

func (x *RspMailList) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMailList.ProtoReflect.Descriptor instead.
func (*RspMailList) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{1}
}

func (x *RspMailList) GetMails() []*PMailDetail {
	if x != nil {
		return x.Mails
	}
	return nil
}

type ReqMailRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailId        int64                  `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqMailRead) Reset() {
	*x = ReqMailRead{}
	mi := &file_mail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqMailRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMailRead) ProtoMessage() {}

func (x *ReqMailRead) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMailRead.ProtoReflect.Descriptor instead.
func (*ReqMailRead) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{2}
}

func (x *ReqMailRead) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type RspMailDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mail          *PMailDetail           `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspMailDetail) Reset() {
	*x = RspMailDetail{}
	mi := &file_mail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspMailDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMailDetail) ProtoMessage() {}

func (x *RspMailDetail) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMailDetail.ProtoReflect.Descriptor instead.
func (*RspMailDetail) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{3}
}

func (x *RspMailDetail) GetMail() *PMailDetail {
	if x != nil {
		return x.Mail
	}
	return nil
}

type PMailDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content"`
	SendAt        int64                  `protobuf:"varint,4,opt,name=send_at,json=sendAt,proto3" json:"send_at"`
	ExpireAt      int64                  `protobuf:"varint,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at"`
	Attachments   []*PGoodInfo           `protobuf:"bytes,6,rep,name=attachments,proto3" json:"attachments"`
	IsRead        bool                   `protobuf:"varint,7,opt,name=is_read,json=isRead,proto3" json:"is_read"`
	IsClaimed     bool                   `protobuf:"varint,8,opt,name=is_claimed,json=isClaimed,proto3" json:"is_claimed"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PMailDetail) Reset() {
	*x = PMailDetail{}
	mi := &file_mail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PMailDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PMailDetail) ProtoMessage() {}

func (x *PMailDetail) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PMailDetail.ProtoReflect.Descriptor instead.
func (*PMailDetail) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{4}
}

func (x *PMailDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PMailDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PMailDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PMailDetail) GetSendAt() int64 {
	if x != nil {
		return x.SendAt
	}
	return 0
}

func (x *PMailDetail) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *PMailDetail) GetAttachments() []*PGoodInfo {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *PMailDetail) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *PMailDetail) GetIsClaimed() bool {
	if x != nil {
		return x.IsClaimed
	}
	return false
}

type ReqMailClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailId        int64                  `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqMailClaim) Reset() {
	*x = ReqMailClaim{}
	mi := &file_mail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqMailClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMailClaim) ProtoMessage() {}

func (x *ReqMailClaim) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMailClaim.ProtoReflect.Descriptor instead.
func (*ReqMailClaim) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{5}
}

func (x *ReqMailClaim) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type RspMailClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mail          *PMailDetail           `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspMailClaim) Reset() {
	*x = RspMailClaim{}
	mi := &file_mail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspMailClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMailClaim) ProtoMessage() {}

func (x *RspMailClaim) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMailClaim.ProtoReflect.Descriptor instead.
func (*RspMailClaim) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{6}
}

func (x *RspMailClaim) GetMail() *PMailDetail {
	if x != nil {
		return x.Mail
	}
	return nil
}

type ReqMailClaimAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqMailClaimAll) Reset() {
	*x = ReqMailClaimAll{}
	mi := &file_mail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqMailClaimAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMailClaimAll) ProtoMessage() {}

func (x *ReqMailClaimAll) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMailClaimAll.ProtoReflect.Descriptor instead.
func (*ReqMailClaimAll) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{7}
}

type RspMailClaimAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mails         []*PMailDetail         `protobuf:"bytes,1,rep,name=mails,proto3" json:"mails"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspMailClaimAll) Reset() {
	*x = RspMailClaimAll{}
	mi := &file_mail_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspMailClaimAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMailClaimAll) ProtoMessage() {}

func (x *RspMailClaimAll) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMailClaimAll.ProtoReflect.Descriptor instead.
func (*RspMailClaimAll) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{8}
}

func (x *RspMailClaimAll) GetMails() []*PMailDetail {
	if x != nil {
		return x.Mails
	}
	return nil
}

type ReqMailDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailId        int64                  `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqMailDelete) Reset() {
	*x = ReqMailDelete{}
	mi := &file_mail_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqMailDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMailDelete) ProtoMessage() {}

func (x *ReqMailDelete) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMailDelete.ProtoReflect.Descriptor instead.
func (*ReqMailDelete) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{9}
}

func (x *ReqMailDelete) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type RspMailDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mail          *PMailDetail           `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspMailDelete) Reset() {
	*x = RspMailDelete{}
	mi := &file_mail_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspMailDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMailDelete) ProtoMessage() {}

func (x *RspMailDelete) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMailDelete.ProtoReflect.Descriptor instead.
func (*RspMailDelete) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{10}
}

func (x *RspMailDelete) GetMail() *PMailDetail {
	if x != nil {
		return x.Mail
	}
	return nil
}

type NotifyMailUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailId        int64                  `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyMailUpdate) Reset() {
	*x = NotifyMailUpdate{}
	mi := &file_mail_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyMailUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyMailUpdate) ProtoMessage() {}

func (x *NotifyMailUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyMailUpdate.ProtoReflect.Descriptor instead.
func (*NotifyMailUpdate) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{11}
}

func (x *NotifyMailUpdate) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

var File_mail_proto protoreflect.FileDescriptor

const file_mail_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mail.proto\x12\x0fgalaxy.protocol\x1a\x11msg_options.proto\x1a\tbag.proto\"\x15\n" +
	"\vReqMailList:\x06\xa8\xac\x1d\xb1\xea\x01\"I\n" +
	"\vRspMailList\x122\n" +
	"\x05mails\x18\x01 \x03(\v2\x1c.galaxy.protocol.PMailDetailR\x05mails:\x06\xa8\xac\x1d\xb2\xea\x01\".\n" +
	"\vReqMailRead\x12\x17\n" +
	"\amail_id\x18\x01 \x01(\x03R\x06mailId:\x06\xa8\xac\x1d\xb3\xea\x01\"I\n" +
	"\rRspMailDetail\x120\n" +
	"\x04mail\x18\x01 \x01(\v2\x1c.galaxy.protocol.PMailDetailR\x04mail:\x06\xa8\xac\x1d\xb4\xea\x01\"\xf9\x01\n" +
	"\vPMailDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x17\n" +
	"\asend_at\x18\x04 \x01(\x03R\x06sendAt\x12\x1b\n" +
	"\texpire_at\x18\x05 \x01(\x03R\bexpireAt\x12<\n" +
	"\vattachments\x18\x06 \x03(\v2\x1a.galaxy.protocol.PGoodInfoR\vattachments\x12\x17\n" +
	"\ais_read\x18\a \x01(\bR\x06isRead\x12\x1d\n" +
	"\n" +
	"is_claimed\x18\b \x01(\bR\tisClaimed\"/\n" +
	"\fReqMailClaim\x12\x17\n" +
	"\amail_id\x18\x01 \x01(\x03R\x06mailId:\x06\xa8\xac\x1d\xb5\xea\x01\"H\n" +
	"\fRspMailClaim\x120\n" +
	"\x04mail\x18\x01 \x01(\v2\x1c.galaxy.protocol.PMailDetailR\x04mail:\x06\xa8\xac\x1d\xb6\xea\x01\"\x19\n" +
	"\x0fReqMailClaimAll:\x06\xa8\xac\x1d\xb7\xea\x01\"M\n" +
	"\x0fRspMailClaimAll\x122\n" +
	"\x05mails\x18\x01 \x03(\v2\x1c.galaxy.protocol.PMailDetailR\x05mails:\x06\xa8\xac\x1d\xb8\xea\x01\"0\n" +
	"\rReqMailDelete\x12\x17\n" +
	"\amail_id\x18\x01 \x01(\x03R\x06mailId:\x06\xa8\xac\x1d\xb9\xea\x01\"I\n" +
	"\rRspMailDelete\x120\n" +
	"\x04mail\x18\x01 \x01(\v2\x1c.galaxy.protocol.PMailDetailR\x04mail:\x06\xa8\xac\x1d\xba\xea\x01\"3\n" +
	"\x10NotifyMailUpdate\x12\x17\n" +
	"\amail_id\x18\x01 \x01(\x03R\x06mailId:\x06\xa8\xac\x1d\xbb\xea\x01B\tZ\a./pb;pbb\x06proto3"

var (
	file_mail_proto_rawDescOnce sync.Once
	file_mail_proto_rawDescData []byte
)

func file_mail_proto_rawDescGZIP() []byte {
	file_mail_proto_rawDescOnce.Do(func() {
		file_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mail_proto_rawDesc), len(file_mail_proto_rawDesc)))
	})
	return file_mail_proto_rawDescData
}

var file_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_mail_proto_goTypes = []any{
	(*ReqMailList)(nil),      // 0: galaxy.protocol.ReqMailList
	(*RspMailList)(nil),      // 1: galaxy.protocol.RspMailList
	(*ReqMailRead)(nil),      // 2: galaxy.protocol.ReqMailRead
	(*RspMailDetail)(nil),    // 3: galaxy.protocol.RspMailDetail
	(*PMailDetail)(nil),      // 4: galaxy.protocol.PMailDetail
	(*ReqMailClaim)(nil),     // 5: galaxy.protocol.ReqMailClaim
	(*RspMailClaim)(nil),     // 6: galaxy.protocol.RspMailClaim
	(*ReqMailClaimAll)(nil),  // 7: galaxy.protocol.ReqMailClaimAll
	(*RspMailClaimAll)(nil),  // 8: galaxy.protocol.RspMailClaimAll
	(*ReqMailDelete)(nil),    // 9: galaxy.protocol.ReqMailDelete
	(*RspMailDelete)(nil),    // 10: galaxy.protocol.RspMailDelete
	(*NotifyMailUpdate)(nil), // 11: galaxy.protocol.NotifyMailUpdate
	(*PGoodInfo)(nil),        // 12: galaxy.protocol.PGoodInfo
}
var file_mail_proto_depIdxs = []int32{
	4,  // 0: galaxy.protocol.RspMailList.mails:type_name -> galaxy.protocol.PMailDetail
	4,  // 1: galaxy.protocol.RspMailDetail.mail:type_name -> galaxy.protocol.PMailDetail
	12, // 2: galaxy.protocol.PMailDetail.attachments:type_name -> galaxy.protocol.PGoodInfo
	4,  // 3: galaxy.protocol.RspMailClaim.mail:type_name -> galaxy.protocol.PMailDetail
	4,  // 4: galaxy.protocol.RspMailClaimAll.mails:type_name -> galaxy.protocol.PMailDetail
	4,  // 5: galaxy.protocol.RspMailDelete.mail:type_name -> galaxy.protocol.PMailDetail
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_mail_proto_init() }
func file_mail_proto_init() {
	if File_mail_proto != nil {
		return
	}
	file_msg_options_proto_init()
	file_bag_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mail_proto_rawDesc), len(file_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mail_proto_goTypes,
		DependencyIndexes: file_mail_proto_depIdxs,
		MessageInfos:      file_mail_proto_msgTypes,
	}.Build()
	File_mail_proto = out.File
	file_mail_proto_goTypes = nil
	file_mail_proto_depIdxs = nil
}
