// ID: 25001~25099

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.3
// source: maintask.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MainTaskStatus int32

const (
	MainTaskStatus_MAIN_TASK_IN_PROGRESS MainTaskStatus = 0
	MainTaskStatus_MAIN_TASK_CLAIMABLE   MainTaskStatus = 1
	MainTaskStatus_MAIN_TASK_FINISHED    MainTaskStatus = 2
)

// Enum value maps for MainTaskStatus.
var (
	MainTaskStatus_name = map[int32]string{
		0: "MAIN_TASK_IN_PROGRESS",
		1: "MAIN_TASK_CLAIMABLE",
		2: "MAIN_TASK_FINISHED",
	}
	MainTaskStatus_value = map[string]int32{
		"MAIN_TASK_IN_PROGRESS": 0,
		"MAIN_TASK_CLAIMABLE":   1,
		"MAIN_TASK_FINISHED":    2,
	}
)

func (x MainTaskStatus) Enum() *MainTaskStatus {
	p := new(MainTaskStatus)
	*p = x
	return p
}

func (x MainTaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MainTaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_maintask_proto_enumTypes[0].Descriptor()
}

func (MainTaskStatus) Type() protoreflect.EnumType {
	return &file_maintask_proto_enumTypes[0]
}

func (x MainTaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MainTaskStatus.Descriptor instead.
func (MainTaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_maintask_proto_rawDescGZIP(), []int{0}
}

type PMainTaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress"`
	Status        MainTaskStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=galaxy.protocol.MainTaskStatus" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PMainTaskInfo) Reset() {
	*x = PMainTaskInfo{}
	mi := &file_maintask_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PMainTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PMainTaskInfo) ProtoMessage() {}

func (x *PMainTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_maintask_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PMainTaskInfo.ProtoReflect.Descriptor instead.
func (*PMainTaskInfo) Descriptor() ([]byte, []int) {
	return file_maintask_proto_rawDescGZIP(), []int{0}
}

func (x *PMainTaskInfo) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *PMainTaskInfo) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *PMainTaskInfo) GetStatus() MainTaskStatus {
	if x != nil {
		return x.Status
	}
	return MainTaskStatus_MAIN_TASK_IN_PROGRESS
}

type ReqMainTaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqMainTaskInfo) Reset() {
	*x = ReqMainTaskInfo{}
	mi := &file_maintask_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqMainTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMainTaskInfo) ProtoMessage() {}

func (x *ReqMainTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_maintask_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMainTaskInfo.ProtoReflect.Descriptor instead.
func (*ReqMainTaskInfo) Descriptor() ([]byte, []int) {
	return file_maintask_proto_rawDescGZIP(), []int{1}
}

type RspMainTaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *PMainTaskInfo         `protobuf:"bytes,1,opt,name=task,proto3" json:"task"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspMainTaskInfo) Reset() {
	*x = RspMainTaskInfo{}
	mi := &file_maintask_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspMainTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMainTaskInfo) ProtoMessage() {}

func (x *RspMainTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_maintask_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMainTaskInfo.ProtoReflect.Descriptor instead.
func (*RspMainTaskInfo) Descriptor() ([]byte, []int) {
	return file_maintask_proto_rawDescGZIP(), []int{2}
}

func (x *RspMainTaskInfo) GetTask() *PMainTaskInfo {
	if x != nil {
		return x.Task
	}
	return nil
}

type ReqMainTaskClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqMainTaskClaim) Reset() {
	*x = ReqMainTaskClaim{}
	mi := &file_maintask_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqMainTaskClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMainTaskClaim) ProtoMessage() {}

func (x *ReqMainTaskClaim) ProtoReflect() protoreflect.Message {
	mi := &file_maintask_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMainTaskClaim.ProtoReflect.Descriptor instead.
func (*ReqMainTaskClaim) Descriptor() ([]byte, []int) {
	return file_maintask_proto_rawDescGZIP(), []int{3}
}

type RspMainTaskClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *PMainTaskInfo         `protobuf:"bytes,1,opt,name=task,proto3" json:"task"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspMainTaskClaim) Reset() {
	*x = RspMainTaskClaim{}
	mi := &file_maintask_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspMainTaskClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMainTaskClaim) ProtoMessage() {}

func (x *RspMainTaskClaim) ProtoReflect() protoreflect.Message {
	mi := &file_maintask_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMainTaskClaim.ProtoReflect.Descriptor instead.
func (*RspMainTaskClaim) Descriptor() ([]byte, []int) {
	return file_maintask_proto_rawDescGZIP(), []int{4}
}

func (x *RspMainTaskClaim) GetTask() *PMainTaskInfo {
	if x != nil {
		return x.Task
	}
	return nil
}

type NotifyMainTaskUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *PMainTaskInfo         `protobuf:"bytes,1,opt,name=task,proto3" json:"task"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyMainTaskUpdate) Reset() {
	*x = NotifyMainTaskUpdate{}
	mi := &file_maintask_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyMainTaskUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyMainTaskUpdate) ProtoMessage() {}

func (x *NotifyMainTaskUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_maintask_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyMainTaskUpdate.ProtoReflect.Descriptor instead.
func (*NotifyMainTaskUpdate) Descriptor() ([]byte, []int) {
	return file_maintask_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyMainTaskUpdate) GetTask() *PMainTaskInfo {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_maintask_proto protoreflect.FileDescriptor

const file_maintask_proto_rawDesc = "" +
	"\n" +
	"\x0emaintask.proto\x12\x0fgalaxy.protocol\x1a\x11msg_options.proto\"}\n" +
	"\rPMainTaskInfo\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x127\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1f.galaxy.protocol.MainTaskStatusR\x06status\"\x19\n" +
	"\x0fReqMainTaskInfo:\x06\xa8\xac\x1d\xa9\xc3\x01\"M\n" +
	"\x0fRspMainTaskInfo\x122\n" +
	"\x04task\x18\x01 \x01(\v2\x1e.galaxy.protocol.PMainTaskInfoR\x04task:\x06\xa8\xac\x1d\xaa\xc3\x01\"\x1a\n" +
	"\x10ReqMainTaskClaim:\x06\xa8\xac\x1d\xab\xc3\x01\"N\n" +
	"\x10RspMainTaskClaim\x122\n" +
	"\x04task\x18\x01 \x01(\v2\x1e.galaxy.protocol.PMainTaskInfoR\x04task:\x06\xa8\xac\x1d\xac\xc3\x01\"R\n" +
	"\x14NotifyMainTaskUpdate\x122\n" +
	"\x04task\x18\x01 \x01(\v2\x1e.galaxy.protocol.PMainTaskInfoR\x04task:\x06\xa8\xac\x1d\xad\xc3\x01*\\\n" +
	"\x0eMainTaskStatus\x12\x19\n" +
	"\x15MAIN_TASK_IN_PROGRESS\x10\x00\x12\x17\n" +
	"\x13MAIN_TASK_CLAIMABLE\x10\x01\x12\x16\n" +
	"\x12MAIN_TASK_FINISHED\x10\x02B\tZ\a./pb;pbb\x06proto3"

var (
	file_maintask_proto_rawDescOnce sync.Once
	file_maintask_proto_rawDescData []byte
)

func file_maintask_proto_rawDescGZIP() []byte {
	file_maintask_proto_rawDescOnce.Do(func() {
		file_maintask_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_maintask_proto_rawDesc), len(file_maintask_proto_rawDesc)))
	})
	return file_maintask_proto_rawDescData
}

var file_maintask_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_maintask_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_maintask_proto_goTypes = []any{
	(MainTaskStatus)(0),          // 0: galaxy.protocol.MainTaskStatus
	(*PMainTaskInfo)(nil),        // 1: galaxy.protocol.PMainTaskInfo
	(*ReqMainTaskInfo)(nil),      // 2: galaxy.protocol.ReqMainTaskInfo
	(*RspMainTaskInfo)(nil),      // 3: galaxy.protocol.RspMainTaskInfo
	(*ReqMainTaskClaim)(nil),     // 4: galaxy.protocol.ReqMainTaskClaim
	(*RspMainTaskClaim)(nil),     // 5: galaxy.protocol.RspMainTaskClaim
	(*NotifyMainTaskUpdate)(nil), // 6: galaxy.protocol.NotifyMainTaskUpdate
}
var file_maintask_proto_depIdxs = []int32{
	0, // 0: galaxy.protocol.PMainTaskInfo.status:type_name -> galaxy.protocol.MainTaskStatus
	1, // 1: galaxy.protocol.RspMainTaskInfo.task:type_name -> galaxy.protocol.PMainTaskInfo
	1, // 2: galaxy.protocol.RspMainTaskClaim.task:type_name -> galaxy.protocol.PMainTaskInfo
	1, // 3: galaxy.protocol.NotifyMainTaskUpdate.task:type_name -> galaxy.protocol.PMainTaskInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_maintask_proto_init() }
func file_maintask_proto_init() {
	if File_maintask_proto != nil {
		return
	}
	file_msg_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_maintask_proto_rawDesc), len(file_maintask_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_maintask_proto_goTypes,
		DependencyIndexes: file_maintask_proto_depIdxs,
		EnumInfos:         file_maintask_proto_enumTypes,
		MessageInfos:      file_maintask_proto_msgTypes,
	}.Build()
	File_maintask_proto = out.File
	file_maintask_proto_goTypes = nil
	file_maintask_proto_depIdxs = nil
}
