// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.3
// source: msg_options.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_msg_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         60101,
		Name:          "galaxy.protocol.msg_id",
		Tag:           "varint,60101,opt,name=msg_id",
		Filename:      "msg_options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional uint32 msg_id = 60101;
	E_MsgId = &file_msg_options_proto_extTypes[0]
)

var File_msg_options_proto protoreflect.FileDescriptor

const file_msg_options_proto_rawDesc = "" +
	"\n" +
	"\x11msg_options.proto\x12\x0fgalaxy.protocol\x1a google/protobuf/descriptor.proto:8\n" +
	"\x06msg_id\x12\x1f.google.protobuf.MessageOptions\x18\xc5\xd5\x03 \x01(\rR\x05msgIdB\tZ\a./pb;pbb\x06proto3"

var file_msg_options_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
}
var file_msg_options_proto_depIdxs = []int32{
	0, // 0: galaxy.protocol.msg_id:extendee -> google.protobuf.MessageOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_options_proto_init() }
func file_msg_options_proto_init() {
	if File_msg_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_options_proto_rawDesc), len(file_msg_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_msg_options_proto_goTypes,
		DependencyIndexes: file_msg_options_proto_depIdxs,
		ExtensionInfos:    file_msg_options_proto_extTypes,
	}.Build()
	File_msg_options_proto = out.File
	file_msg_options_proto_goTypes = nil
	file_msg_options_proto_depIdxs = nil
}
