// ID: 24001~24099

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.0
// source: plot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlotState int32

const (
	PlotState_PLOT_EMPTY       PlotState = 0
	PlotState_PLOT_PLANTED     PlotState = 1
	PlotState_PLOT_GROWING     PlotState = 2
	PlotState_PLOT_HARVESTABLE PlotState = 3
)

// Enum value maps for PlotState.
var (
	PlotState_name = map[int32]string{
		0: "PLOT_EMPTY",
		1: "PLOT_PLANTED",
		2: "PLOT_GROWING",
		3: "PLOT_HARVESTABLE",
	}
	PlotState_value = map[string]int32{
		"PLOT_EMPTY":       0,
		"PLOT_PLANTED":     1,
		"PLOT_GROWING":     2,
		"PLOT_HARVESTABLE": 3,
	}
)

func (x PlotState) Enum() *PlotState {
	p := new(PlotState)
	*p = x
	return p
}

func (x PlotState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlotState) Descriptor() protoreflect.EnumDescriptor {
	return file_plot_proto_enumTypes[0].Descriptor()
}

func (PlotState) Type() protoreflect.EnumType {
	return &file_plot_proto_enumTypes[0]
}

func (x PlotState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlotState.Descriptor instead.
func (PlotState) EnumDescriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{0}
}

type PPlotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlotId       int32     `protobuf:"varint,1,opt,name=plot_id,json=plotId,proto3" json:"plot_id"`
	FlowerId     int32     `protobuf:"varint,2,opt,name=flower_id,json=flowerId,proto3" json:"flower_id"`
	State        PlotState `protobuf:"varint,3,opt,name=state,proto3,enum=galaxy.protocol.PlotState" json:"state"`
	HarvestCount int32     `protobuf:"varint,4,opt,name=harvest_count,json=harvestCount,proto3" json:"harvest_count"`
	StateTime    int64     `protobuf:"varint,5,opt,name=state_time,json=stateTime,proto3" json:"state_time"`
	CanSteal     bool      `protobuf:"varint,6,opt,name=can_steal,json=canSteal,proto3" json:"can_steal"`
}

func (x *PPlotInfo) Reset() {
	*x = PPlotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PPlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPlotInfo) ProtoMessage() {}

func (x *PPlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPlotInfo.ProtoReflect.Descriptor instead.
func (*PPlotInfo) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{0}
}

func (x *PPlotInfo) GetPlotId() int32 {
	if x != nil {
		return x.PlotId
	}
	return 0
}

func (x *PPlotInfo) GetFlowerId() int32 {
	if x != nil {
		return x.FlowerId
	}
	return 0
}

func (x *PPlotInfo) GetState() PlotState {
	if x != nil {
		return x.State
	}
	return PlotState_PLOT_EMPTY
}

func (x *PPlotInfo) GetHarvestCount() int32 {
	if x != nil {
		return x.HarvestCount
	}
	return 0
}

func (x *PPlotInfo) GetStateTime() int64 {
	if x != nil {
		return x.StateTime
	}
	return 0
}

func (x *PPlotInfo) GetCanSteal() bool {
	if x != nil {
		return x.CanSteal
	}
	return false
}

// 地块信息 (24001)
type ReqPlotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqPlotInfo) Reset() {
	*x = ReqPlotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPlotInfo) ProtoMessage() {}

func (x *ReqPlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPlotInfo.ProtoReflect.Descriptor instead.
func (*ReqPlotInfo) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{1}
}

type RspPlotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plots []*PPlotInfo `protobuf:"bytes,1,rep,name=plots,proto3" json:"plots"`
}

func (x *RspPlotInfo) Reset() {
	*x = RspPlotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspPlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPlotInfo) ProtoMessage() {}

func (x *RspPlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPlotInfo.ProtoReflect.Descriptor instead.
func (*RspPlotInfo) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{2}
}

func (x *RspPlotInfo) GetPlots() []*PPlotInfo {
	if x != nil {
		return x.Plots
	}
	return nil
}

// 解锁地块 (24003)
type ReqPlotUnlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlotId int32 `protobuf:"varint,1,opt,name=plot_id,json=plotId,proto3" json:"plot_id"`
}

func (x *ReqPlotUnlock) Reset() {
	*x = ReqPlotUnlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPlotUnlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPlotUnlock) ProtoMessage() {}

func (x *ReqPlotUnlock) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPlotUnlock.ProtoReflect.Descriptor instead.
func (*ReqPlotUnlock) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{3}
}

func (x *ReqPlotUnlock) GetPlotId() int32 {
	if x != nil {
		return x.PlotId
	}
	return 0
}

type RspPlotUnlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plot *PPlotInfo `protobuf:"bytes,1,opt,name=plot,proto3" json:"plot"`
}

func (x *RspPlotUnlock) Reset() {
	*x = RspPlotUnlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspPlotUnlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPlotUnlock) ProtoMessage() {}

func (x *RspPlotUnlock) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPlotUnlock.ProtoReflect.Descriptor instead.
func (*RspPlotUnlock) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{4}
}

func (x *RspPlotUnlock) GetPlot() *PPlotInfo {
	if x != nil {
		return x.Plot
	}
	return nil
}

// 种植 (24005)
type ReqPlotPlant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlotIds  []int32 `protobuf:"varint,1,rep,packed,name=plot_ids,json=plotIds,proto3" json:"plot_ids"`
	FlowerId int32   `protobuf:"varint,2,opt,name=flower_id,json=flowerId,proto3" json:"flower_id"`
}

func (x *ReqPlotPlant) Reset() {
	*x = ReqPlotPlant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPlotPlant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPlotPlant) ProtoMessage() {}

func (x *ReqPlotPlant) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPlotPlant.ProtoReflect.Descriptor instead.
func (*ReqPlotPlant) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{5}
}

func (x *ReqPlotPlant) GetPlotIds() []int32 {
	if x != nil {
		return x.PlotIds
	}
	return nil
}

func (x *ReqPlotPlant) GetFlowerId() int32 {
	if x != nil {
		return x.FlowerId
	}
	return 0
}

type RspPlotPlant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plots []*PPlotInfo `protobuf:"bytes,1,rep,name=plots,proto3" json:"plots"`
}

func (x *RspPlotPlant) Reset() {
	*x = RspPlotPlant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspPlotPlant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPlotPlant) ProtoMessage() {}

func (x *RspPlotPlant) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPlotPlant.ProtoReflect.Descriptor instead.
func (*RspPlotPlant) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{6}
}

func (x *RspPlotPlant) GetPlots() []*PPlotInfo {
	if x != nil {
		return x.Plots
	}
	return nil
}

// 浇水 (24007)
type ReqPlotWater struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlotIds []int32 `protobuf:"varint,1,rep,packed,name=plot_ids,json=plotIds,proto3" json:"plot_ids"`
}

func (x *ReqPlotWater) Reset() {
	*x = ReqPlotWater{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPlotWater) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPlotWater) ProtoMessage() {}

func (x *ReqPlotWater) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPlotWater.ProtoReflect.Descriptor instead.
func (*ReqPlotWater) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{7}
}

func (x *ReqPlotWater) GetPlotIds() []int32 {
	if x != nil {
		return x.PlotIds
	}
	return nil
}

type RspPlotWater struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plots []*PPlotInfo `protobuf:"bytes,1,rep,name=plots,proto3" json:"plots"`
}

func (x *RspPlotWater) Reset() {
	*x = RspPlotWater{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspPlotWater) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPlotWater) ProtoMessage() {}

func (x *RspPlotWater) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPlotWater.ProtoReflect.Descriptor instead.
func (*RspPlotWater) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{8}
}

func (x *RspPlotWater) GetPlots() []*PPlotInfo {
	if x != nil {
		return x.Plots
	}
	return nil
}

// 收获 (24009)
type ReqPlotHarvest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlotIds []int32 `protobuf:"varint,1,rep,packed,name=plot_ids,json=plotIds,proto3" json:"plot_ids"`
}

func (x *ReqPlotHarvest) Reset() {
	*x = ReqPlotHarvest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPlotHarvest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPlotHarvest) ProtoMessage() {}

func (x *ReqPlotHarvest) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPlotHarvest.ProtoReflect.Descriptor instead.
func (*ReqPlotHarvest) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{9}
}

func (x *ReqPlotHarvest) GetPlotIds() []int32 {
	if x != nil {
		return x.PlotIds
	}
	return nil
}

type RspPlotHarvest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plots []*PPlotInfo `protobuf:"bytes,1,rep,name=plots,proto3" json:"plots"`
}

func (x *RspPlotHarvest) Reset() {
	*x = RspPlotHarvest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspPlotHarvest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPlotHarvest) ProtoMessage() {}

func (x *RspPlotHarvest) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPlotHarvest.ProtoReflect.Descriptor instead.
func (*RspPlotHarvest) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{10}
}

func (x *RspPlotHarvest) GetPlots() []*PPlotInfo {
	if x != nil {
		return x.Plots
	}
	return nil
}

// 移除种植 (24011)
type ReqPlotRemove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlotIds []int32 `protobuf:"varint,1,rep,packed,name=plot_ids,json=plotIds,proto3" json:"plot_ids"`
}

func (x *ReqPlotRemove) Reset() {
	*x = ReqPlotRemove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPlotRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPlotRemove) ProtoMessage() {}

func (x *ReqPlotRemove) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPlotRemove.ProtoReflect.Descriptor instead.
func (*ReqPlotRemove) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{11}
}

func (x *ReqPlotRemove) GetPlotIds() []int32 {
	if x != nil {
		return x.PlotIds
	}
	return nil
}

type RspPlotRemove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plots []*PPlotInfo `protobuf:"bytes,1,rep,name=plots,proto3" json:"plots"`
}

func (x *RspPlotRemove) Reset() {
	*x = RspPlotRemove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspPlotRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPlotRemove) ProtoMessage() {}

func (x *RspPlotRemove) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPlotRemove.ProtoReflect.Descriptor instead.
func (*RspPlotRemove) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{12}
}

func (x *RspPlotRemove) GetPlots() []*PPlotInfo {
	if x != nil {
		return x.Plots
	}
	return nil
}

// 查看好友花园 (24013)
type ReqPlotFriendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId int64 `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id"`
}

func (x *ReqPlotFriendInfo) Reset() {
	*x = ReqPlotFriendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPlotFriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPlotFriendInfo) ProtoMessage() {}

func (x *ReqPlotFriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPlotFriendInfo.ProtoReflect.Descriptor instead.
func (*ReqPlotFriendInfo) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{13}
}

func (x *ReqPlotFriendInfo) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type RspPlotFriendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plots      []*PPlotInfo `protobuf:"bytes,1,rep,name=plots,proto3" json:"plots"`
	StealUsed  int32        `protobuf:"varint,2,opt,name=steal_used,json=stealUsed,proto3" json:"steal_used"`
	StealLimit int32        `protobuf:"varint,3,opt,name=steal_limit,json=stealLimit,proto3" json:"steal_limit"`
}

func (x *RspPlotFriendInfo) Reset() {
	*x = RspPlotFriendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspPlotFriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPlotFriendInfo) ProtoMessage() {}

func (x *RspPlotFriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPlotFriendInfo.ProtoReflect.Descriptor instead.
func (*RspPlotFriendInfo) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{14}
}

func (x *RspPlotFriendInfo) GetPlots() []*PPlotInfo {
	if x != nil {
		return x.Plots
	}
	return nil
}

func (x *RspPlotFriendInfo) GetStealUsed() int32 {
	if x != nil {
		return x.StealUsed
	}
	return 0
}

func (x *RspPlotFriendInfo) GetStealLimit() int32 {
	if x != nil {
		return x.StealLimit
	}
	return 0
}

// 偷花 (24015)
type ReqPlotSteal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId int64 `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id"`
	PlotId   int32 `protobuf:"varint,2,opt,name=plot_id,json=plotId,proto3" json:"plot_id"`
}

func (x *ReqPlotSteal) Reset() {
	*x = ReqPlotSteal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPlotSteal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPlotSteal) ProtoMessage() {}

func (x *ReqPlotSteal) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPlotSteal.ProtoReflect.Descriptor instead.
func (*ReqPlotSteal) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{15}
}

func (x *ReqPlotSteal) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *ReqPlotSteal) GetPlotId() int32 {
	if x != nil {
		return x.PlotId
	}
	return 0
}

type RspPlotSteal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Rewards []*PGoodInfo `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards"`
}

func (x *RspPlotSteal) Reset() {
	*x = RspPlotSteal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspPlotSteal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPlotSteal) ProtoMessage() {}

func (x *RspPlotSteal) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPlotSteal.ProtoReflect.Descriptor instead.
func (*RspPlotSteal) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{16}
}

func (x *RspPlotSteal) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RspPlotSteal) GetRewards() []*PGoodInfo {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_plot_proto protoreflect.FileDescriptor

var file_plot_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x6c, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x61,
	0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x11, 0x6d,
	0x73, 0x67, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x09, 0x62, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd4, 0x01, 0x0a, 0x09,
	0x50, 0x50, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x6f,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c, 0x6f, 0x74,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a,
	0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x50, 0x6c, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x61, 0x72, 0x76, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x68, 0x61, 0x72, 0x76, 0x65, 0x73,
	0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x5f, 0x73, 0x74, 0x65,
	0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x61, 0x6e, 0x53, 0x74, 0x65,
	0x61, 0x6c, 0x22, 0x15, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x50, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xc1, 0xbb, 0x01, 0x22, 0x47, 0x0a, 0x0b, 0x52, 0x73, 0x70,
	0x50, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x30, 0x0a, 0x05, 0x70, 0x6c, 0x6f, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x50, 0x6c, 0x6f, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x05, 0x70, 0x6c, 0x6f, 0x74, 0x73, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xc2,
	0xbb, 0x01, 0x22, 0x30, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x50, 0x6c, 0x6f, 0x74, 0x55, 0x6e, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x3a, 0x06, 0xa8, 0xac,
	0x1d, 0xc3, 0xbb, 0x01, 0x22, 0x47, 0x0a, 0x0d, 0x52, 0x73, 0x70, 0x50, 0x6c, 0x6f, 0x74, 0x55,
	0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x2e, 0x0a, 0x04, 0x70, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x50, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x70, 0x6c, 0x6f, 0x74, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xc4, 0xbb, 0x01, 0x22, 0x4e, 0x0a,
	0x0c, 0x52, 0x65, 0x71, 0x50, 0x6c, 0x6f, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x70, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x07, 0x70, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6c, 0x6f, 0x77,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x6c, 0x6f,
	0x77, 0x65, 0x72, 0x49, 0x64, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xc5, 0xbb, 0x01, 0x22, 0x48, 0x0a,
	0x0c, 0x52, 0x73, 0x70, 0x50, 0x6c, 0x6f, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x30, 0x0a,
	0x05, 0x70, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50,
	0x50, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x70, 0x6c, 0x6f, 0x74, 0x73, 0x3a,
	0x06, 0xa8, 0xac, 0x1d, 0xc6, 0xbb, 0x01, 0x22, 0x31, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x50, 0x6c,
	0x6f, 0x74, 0x57, 0x61, 0x74, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x6f, 0x74, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6c, 0x6f, 0x74, 0x49,
	0x64, 0x73, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xc7, 0xbb, 0x01, 0x22, 0x48, 0x0a, 0x0c, 0x52, 0x73,
	0x70, 0x50, 0x6c, 0x6f, 0x74, 0x57, 0x61, 0x74, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x05, 0x70, 0x6c,
	0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6c, 0x61,
	0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x50, 0x6c, 0x6f,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x70, 0x6c, 0x6f, 0x74, 0x73, 0x3a, 0x06, 0xa8, 0xac,
	0x1d, 0xc8, 0xbb, 0x01, 0x22, 0x33, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x50, 0x6c, 0x6f, 0x74, 0x48,
	0x61, 0x72, 0x76, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x6f, 0x74, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6c, 0x6f, 0x74, 0x49, 0x64,
	0x73, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xc9, 0xbb, 0x01, 0x22, 0x4a, 0x0a, 0x0e, 0x52, 0x73, 0x70,
	0x50, 0x6c, 0x6f, 0x74, 0x48, 0x61, 0x72, 0x76, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x70,
	0x6c, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6c,
	0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x50, 0x6c,
	0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x70, 0x6c, 0x6f, 0x74, 0x73, 0x3a, 0x06, 0xa8,
	0xac, 0x1d, 0xca, 0xbb, 0x01, 0x22, 0x32, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x50, 0x6c, 0x6f, 0x74,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x6f, 0x74, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6c, 0x6f, 0x74, 0x49, 0x64,
	0x73, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xcb, 0xbb, 0x01, 0x22, 0x49, 0x0a, 0x0d, 0x52, 0x73, 0x70,
	0x50, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x70, 0x6c,
	0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6c, 0x61,
	0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x50, 0x6c, 0x6f,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x70, 0x6c, 0x6f, 0x74, 0x73, 0x3a, 0x06, 0xa8, 0xac,
	0x1d, 0xcc, 0xbb, 0x01, 0x22, 0x38, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x50, 0x6c, 0x6f, 0x74, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xcd, 0xbb, 0x01, 0x22, 0x8d,
	0x01, 0x0a, 0x11, 0x52, 0x73, 0x70, 0x50, 0x6c, 0x6f, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x30, 0x0a, 0x05, 0x70, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x50, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x70, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x65, 0x61, 0x6c, 0x5f,
	0x75, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x65, 0x61,
	0x6c, 0x55, 0x73, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x65, 0x61, 0x6c, 0x5f, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x65, 0x61,
	0x6c, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xce, 0xbb, 0x01, 0x22, 0x4c,
	0x0a, 0x0c, 0x52, 0x65, 0x71, 0x50, 0x6c, 0x6f, 0x74, 0x53, 0x74, 0x65, 0x61, 0x6c, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70,
	0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c,
	0x6f, 0x74, 0x49, 0x64, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0xcf, 0xbb, 0x01, 0x22, 0x66, 0x0a, 0x0c,
	0x52, 0x73, 0x70, 0x50, 0x6c, 0x6f, 0x74, 0x53, 0x74, 0x65, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x47, 0x6f, 0x6f, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x3a, 0x06, 0xa8, 0xac,
	0x1d, 0xd0, 0xbb, 0x01, 0x2a, 0x55, 0x0a, 0x09, 0x50, 0x6c, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x4c, 0x4f, 0x54, 0x5f, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x4c, 0x4f, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x4e, 0x54, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x4c, 0x4f, 0x54, 0x5f, 0x47, 0x52, 0x4f, 0x57,
	0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x4c, 0x4f, 0x54, 0x5f, 0x48, 0x41,
	0x52, 0x56, 0x45, 0x53, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x03, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plot_proto_rawDescOnce sync.Once
	file_plot_proto_rawDescData = file_plot_proto_rawDesc
)

func file_plot_proto_rawDescGZIP() []byte {
	file_plot_proto_rawDescOnce.Do(func() {
		file_plot_proto_rawDescData = protoimpl.X.CompressGZIP(file_plot_proto_rawDescData)
	})
	return file_plot_proto_rawDescData
}

var file_plot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plot_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_plot_proto_goTypes = []interface{}{
	(PlotState)(0),            // 0: galaxy.protocol.PlotState
	(*PPlotInfo)(nil),         // 1: galaxy.protocol.PPlotInfo
	(*ReqPlotInfo)(nil),       // 2: galaxy.protocol.ReqPlotInfo
	(*RspPlotInfo)(nil),       // 3: galaxy.protocol.RspPlotInfo
	(*ReqPlotUnlock)(nil),     // 4: galaxy.protocol.ReqPlotUnlock
	(*RspPlotUnlock)(nil),     // 5: galaxy.protocol.RspPlotUnlock
	(*ReqPlotPlant)(nil),      // 6: galaxy.protocol.ReqPlotPlant
	(*RspPlotPlant)(nil),      // 7: galaxy.protocol.RspPlotPlant
	(*ReqPlotWater)(nil),      // 8: galaxy.protocol.ReqPlotWater
	(*RspPlotWater)(nil),      // 9: galaxy.protocol.RspPlotWater
	(*ReqPlotHarvest)(nil),    // 10: galaxy.protocol.ReqPlotHarvest
	(*RspPlotHarvest)(nil),    // 11: galaxy.protocol.RspPlotHarvest
	(*ReqPlotRemove)(nil),     // 12: galaxy.protocol.ReqPlotRemove
	(*RspPlotRemove)(nil),     // 13: galaxy.protocol.RspPlotRemove
	(*ReqPlotFriendInfo)(nil), // 14: galaxy.protocol.ReqPlotFriendInfo
	(*RspPlotFriendInfo)(nil), // 15: galaxy.protocol.RspPlotFriendInfo
	(*ReqPlotSteal)(nil),      // 16: galaxy.protocol.ReqPlotSteal
	(*RspPlotSteal)(nil),      // 17: galaxy.protocol.RspPlotSteal
	(*PGoodInfo)(nil),         // 18: galaxy.protocol.PGoodInfo
}
var file_plot_proto_depIdxs = []int32{
	0,  // 0: galaxy.protocol.PPlotInfo.state:type_name -> galaxy.protocol.PlotState
	1,  // 1: galaxy.protocol.RspPlotInfo.plots:type_name -> galaxy.protocol.PPlotInfo
	1,  // 2: galaxy.protocol.RspPlotUnlock.plot:type_name -> galaxy.protocol.PPlotInfo
	1,  // 3: galaxy.protocol.RspPlotPlant.plots:type_name -> galaxy.protocol.PPlotInfo
	1,  // 4: galaxy.protocol.RspPlotWater.plots:type_name -> galaxy.protocol.PPlotInfo
	1,  // 5: galaxy.protocol.RspPlotHarvest.plots:type_name -> galaxy.protocol.PPlotInfo
	1,  // 6: galaxy.protocol.RspPlotRemove.plots:type_name -> galaxy.protocol.PPlotInfo
	1,  // 7: galaxy.protocol.RspPlotFriendInfo.plots:type_name -> galaxy.protocol.PPlotInfo
	18, // 8: galaxy.protocol.RspPlotSteal.rewards:type_name -> galaxy.protocol.PGoodInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_plot_proto_init() }
func file_plot_proto_init() {
	if File_plot_proto != nil {
		return
	}
	file_msg_options_proto_init()
	file_bag_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_plot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PPlotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPlotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspPlotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPlotUnlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspPlotUnlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPlotPlant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspPlotPlant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPlotWater); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspPlotWater); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPlotHarvest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspPlotHarvest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPlotRemove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspPlotRemove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPlotFriendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspPlotFriendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPlotSteal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspPlotSteal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plot_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plot_proto_goTypes,
		DependencyIndexes: file_plot_proto_depIdxs,
		EnumInfos:         file_plot_proto_enumTypes,
		MessageInfos:      file_plot_proto_msgTypes,
	}.Build()
	File_plot_proto = out.File
	file_plot_proto_rawDesc = nil
	file_plot_proto_goTypes = nil
	file_plot_proto_depIdxs = nil
}
