// ID: 26001~26099

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.0
// source: residentorder.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PResidentOrderSlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotId       int32        `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id"`
	Position     int32        `protobuf:"varint,2,opt,name=position,proto3" json:"position"`
	ResidentId   int32        `protobuf:"varint,3,opt,name=resident_id,json=residentId,proto3" json:"resident_id"`
	ResidentName string       `protobuf:"bytes,4,opt,name=resident_name,json=residentName,proto3" json:"resident_name"`
	ResidentDesc string       `protobuf:"bytes,5,opt,name=resident_desc,json=residentDesc,proto3" json:"resident_desc"`
	Demands      []*PGoodInfo `protobuf:"bytes,6,rep,name=demands,proto3" json:"demands"`
	Reward       []*PGoodInfo `protobuf:"bytes,7,rep,name=reward,proto3" json:"reward"`
	CoolDownEnd  int64        `protobuf:"varint,8,opt,name=cool_down_end,json=coolDownEnd,proto3" json:"cool_down_end"`
}

func (x *PResidentOrderSlot) Reset() {
	*x = PResidentOrderSlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_residentorder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResidentOrderSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResidentOrderSlot) ProtoMessage() {}

func (x *PResidentOrderSlot) ProtoReflect() protoreflect.Message {
	mi := &file_residentorder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResidentOrderSlot.ProtoReflect.Descriptor instead.
func (*PResidentOrderSlot) Descriptor() ([]byte, []int) {
	return file_residentorder_proto_rawDescGZIP(), []int{0}
}

func (x *PResidentOrderSlot) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *PResidentOrderSlot) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *PResidentOrderSlot) GetResidentId() int32 {
	if x != nil {
		return x.ResidentId
	}
	return 0
}

func (x *PResidentOrderSlot) GetResidentName() string {
	if x != nil {
		return x.ResidentName
	}
	return ""
}

func (x *PResidentOrderSlot) GetResidentDesc() string {
	if x != nil {
		return x.ResidentDesc
	}
	return ""
}

func (x *PResidentOrderSlot) GetDemands() []*PGoodInfo {
	if x != nil {
		return x.Demands
	}
	return nil
}

func (x *PResidentOrderSlot) GetReward() []*PGoodInfo {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *PResidentOrderSlot) GetCoolDownEnd() int64 {
	if x != nil {
		return x.CoolDownEnd
	}
	return 0
}

type PResidentOrderMilestone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	NeedCount int32 `protobuf:"varint,2,opt,name=need_count,json=needCount,proto3" json:"need_count"`
	Claimed   bool  `protobuf:"varint,3,opt,name=claimed,proto3" json:"claimed"`
}

func (x *PResidentOrderMilestone) Reset() {
	*x = PResidentOrderMilestone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_residentorder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResidentOrderMilestone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResidentOrderMilestone) ProtoMessage() {}

func (x *PResidentOrderMilestone) ProtoReflect() protoreflect.Message {
	mi := &file_residentorder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResidentOrderMilestone.ProtoReflect.Descriptor instead.
func (*PResidentOrderMilestone) Descriptor() ([]byte, []int) {
	return file_residentorder_proto_rawDescGZIP(), []int{1}
}

func (x *PResidentOrderMilestone) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PResidentOrderMilestone) GetNeedCount() int32 {
	if x != nil {
		return x.NeedCount
	}
	return 0
}

func (x *PResidentOrderMilestone) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

// 订单信息 (26001)
type ReqResidentOrderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqResidentOrderInfo) Reset() {
	*x = ReqResidentOrderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_residentorder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqResidentOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqResidentOrderInfo) ProtoMessage() {}

func (x *ReqResidentOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_residentorder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqResidentOrderInfo.ProtoReflect.Descriptor instead.
func (*ReqResidentOrderInfo) Descriptor() ([]byte, []int) {
	return file_residentorder_proto_rawDescGZIP(), []int{2}
}

type RspResidentOrderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slots          []*PResidentOrderSlot      `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots"`
	CompletedCount int32                      `protobuf:"varint,2,opt,name=completed_count,json=completedCount,proto3" json:"completed_count"`
	Milestones     []*PResidentOrderMilestone `protobuf:"bytes,3,rep,name=milestones,proto3" json:"milestones"`
}

func (x *RspResidentOrderInfo) Reset() {
	*x = RspResidentOrderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_residentorder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspResidentOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspResidentOrderInfo) ProtoMessage() {}

func (x *RspResidentOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_residentorder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspResidentOrderInfo.ProtoReflect.Descriptor instead.
func (*RspResidentOrderInfo) Descriptor() ([]byte, []int) {
	return file_residentorder_proto_rawDescGZIP(), []int{3}
}

func (x *RspResidentOrderInfo) GetSlots() []*PResidentOrderSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *RspResidentOrderInfo) GetCompletedCount() int32 {
	if x != nil {
		return x.CompletedCount
	}
	return 0
}

func (x *RspResidentOrderInfo) GetMilestones() []*PResidentOrderMilestone {
	if x != nil {
		return x.Milestones
	}
	return nil
}

// 提交订单 (26003)
type ReqResidentOrderSubmit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotId int32 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id"`
}

func (x *ReqResidentOrderSubmit) Reset() {
	*x = ReqResidentOrderSubmit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_residentorder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqResidentOrderSubmit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqResidentOrderSubmit) ProtoMessage() {}

func (x *ReqResidentOrderSubmit) ProtoReflect() protoreflect.Message {
	mi := &file_residentorder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqResidentOrderSubmit.ProtoReflect.Descriptor instead.
func (*ReqResidentOrderSubmit) Descriptor() ([]byte, []int) {
	return file_residentorder_proto_rawDescGZIP(), []int{4}
}

func (x *ReqResidentOrderSubmit) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type RspResidentOrderSubmit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot           *PResidentOrderSlot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot"`
	CompletedCount int32               `protobuf:"varint,2,opt,name=completed_count,json=completedCount,proto3" json:"completed_count"`
}

func (x *RspResidentOrderSubmit) Reset() {
	*x = RspResidentOrderSubmit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_residentorder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspResidentOrderSubmit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspResidentOrderSubmit) ProtoMessage() {}

func (x *RspResidentOrderSubmit) ProtoReflect() protoreflect.Message {
	mi := &file_residentorder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspResidentOrderSubmit.ProtoReflect.Descriptor instead.
func (*RspResidentOrderSubmit) Descriptor() ([]byte, []int) {
	return file_residentorder_proto_rawDescGZIP(), []int{5}
}

func (x *RspResidentOrderSubmit) GetSlot() *PResidentOrderSlot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *RspResidentOrderSubmit) GetCompletedCount() int32 {
	if x != nil {
		return x.CompletedCount
	}
	return 0
}

// 领取里程碑奖励 (26005)
type ReqResidentOrderClaimMilestone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (x *ReqResidentOrderClaimMilestone) Reset() {
	*x = ReqResidentOrderClaimMilestone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_residentorder_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqResidentOrderClaimMilestone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqResidentOrderClaimMilestone) ProtoMessage() {}

func (x *ReqResidentOrderClaimMilestone) ProtoReflect() protoreflect.Message {
	mi := &file_residentorder_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqResidentOrderClaimMilestone.ProtoReflect.Descriptor instead.
func (*ReqResidentOrderClaimMilestone) Descriptor() ([]byte, []int) {
	return file_residentorder_proto_rawDescGZIP(), []int{6}
}

func (x *ReqResidentOrderClaimMilestone) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RspResidentOrderClaimMilestone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RspResidentOrderClaimMilestone) Reset() {
	*x = RspResidentOrderClaimMilestone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_residentorder_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspResidentOrderClaimMilestone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspResidentOrderClaimMilestone) ProtoMessage() {}

func (x *RspResidentOrderClaimMilestone) ProtoReflect() protoreflect.Message {
	mi := &file_residentorder_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspResidentOrderClaimMilestone.ProtoReflect.Descriptor instead.
func (*RspResidentOrderClaimMilestone) Descriptor() ([]byte, []int) {
	return file_residentorder_proto_rawDescGZIP(), []int{7}
}

var File_residentorder_proto protoreflect.FileDescriptor

var file_residentorder_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x11, 0x6d, 0x73, 0x67, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x62, 0x61, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc2, 0x02, 0x0a, 0x12, 0x50, 0x52, 0x65, 0x73, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6c,
	0x6f, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x73, 0x63, 0x12, 0x34, 0x0a, 0x07, 0x64,
	0x65, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50,
	0x47, 0x6f, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64,
	0x73, 0x12, 0x32, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x63, 0x6f, 0x6f, 0x6c, 0x5f, 0x64, 0x6f,
	0x77, 0x6e, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x6f,
	0x6f, 0x6c, 0x44, 0x6f, 0x77, 0x6e, 0x45, 0x6e, 0x64, 0x22, 0x62, 0x0a, 0x17, 0x50, 0x52, 0x65,
	0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x69, 0x6c, 0x65, 0x73,
	0x74, 0x6f, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6e, 0x65, 0x65, 0x64, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x22, 0x1e, 0x0a,
	0x14, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0x91, 0xcb, 0x01, 0x22, 0xcc, 0x01,
	0x0a, 0x14, 0x52, 0x73, 0x70, 0x52, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x39, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x52, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74,
	0x73, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x48, 0x0a, 0x0a, 0x6d, 0x69,
	0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x50, 0x52, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d,
	0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x52, 0x0a, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x74,
	0x6f, 0x6e, 0x65, 0x73, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0x92, 0xcb, 0x01, 0x22, 0x39, 0x0a, 0x16,
	0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x3a,
	0x06, 0xa8, 0xac, 0x1d, 0x93, 0xcb, 0x01, 0x22, 0x82, 0x01, 0x0a, 0x16, 0x52, 0x73, 0x70, 0x52,
	0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x12, 0x37, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x50, 0x52, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0x94, 0xcb, 0x01, 0x22, 0x38, 0x0a, 0x1e,
	0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x3a, 0x06,
	0xa8, 0xac, 0x1d, 0x95, 0xcb, 0x01, 0x22, 0x28, 0x0a, 0x1e, 0x52, 0x73, 0x70, 0x52, 0x65, 0x73,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4d,
	0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x3a, 0x06, 0xa8, 0xac, 0x1d, 0x96, 0xcb, 0x01,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_residentorder_proto_rawDescOnce sync.Once
	file_residentorder_proto_rawDescData = file_residentorder_proto_rawDesc
)

func file_residentorder_proto_rawDescGZIP() []byte {
	file_residentorder_proto_rawDescOnce.Do(func() {
		file_residentorder_proto_rawDescData = protoimpl.X.CompressGZIP(file_residentorder_proto_rawDescData)
	})
	return file_residentorder_proto_rawDescData
}

var file_residentorder_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_residentorder_proto_goTypes = []interface{}{
	(*PResidentOrderSlot)(nil),             // 0: galaxy.protocol.PResidentOrderSlot
	(*PResidentOrderMilestone)(nil),        // 1: galaxy.protocol.PResidentOrderMilestone
	(*ReqResidentOrderInfo)(nil),           // 2: galaxy.protocol.ReqResidentOrderInfo
	(*RspResidentOrderInfo)(nil),           // 3: galaxy.protocol.RspResidentOrderInfo
	(*ReqResidentOrderSubmit)(nil),         // 4: galaxy.protocol.ReqResidentOrderSubmit
	(*RspResidentOrderSubmit)(nil),         // 5: galaxy.protocol.RspResidentOrderSubmit
	(*ReqResidentOrderClaimMilestone)(nil), // 6: galaxy.protocol.ReqResidentOrderClaimMilestone
	(*RspResidentOrderClaimMilestone)(nil), // 7: galaxy.protocol.RspResidentOrderClaimMilestone
	(*PGoodInfo)(nil),                      // 8: galaxy.protocol.PGoodInfo
}
var file_residentorder_proto_depIdxs = []int32{
	8, // 0: galaxy.protocol.PResidentOrderSlot.demands:type_name -> galaxy.protocol.PGoodInfo
	8, // 1: galaxy.protocol.PResidentOrderSlot.reward:type_name -> galaxy.protocol.PGoodInfo
	0, // 2: galaxy.protocol.RspResidentOrderInfo.slots:type_name -> galaxy.protocol.PResidentOrderSlot
	1, // 3: galaxy.protocol.RspResidentOrderInfo.milestones:type_name -> galaxy.protocol.PResidentOrderMilestone
	0, // 4: galaxy.protocol.RspResidentOrderSubmit.slot:type_name -> galaxy.protocol.PResidentOrderSlot
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_residentorder_proto_init() }
func file_residentorder_proto_init() {
	if File_residentorder_proto != nil {
		return
	}
	file_msg_options_proto_init()
	file_bag_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_residentorder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResidentOrderSlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_residentorder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResidentOrderMilestone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_residentorder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqResidentOrderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_residentorder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspResidentOrderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_residentorder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqResidentOrderSubmit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_residentorder_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspResidentOrderSubmit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_residentorder_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqResidentOrderClaimMilestone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_residentorder_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspResidentOrderClaimMilestone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_residentorder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_residentorder_proto_goTypes,
		DependencyIndexes: file_residentorder_proto_depIdxs,
		MessageInfos:      file_residentorder_proto_msgTypes,
	}.Build()
	File_residentorder_proto = out.File
	file_residentorder_proto_rawDesc = nil
	file_residentorder_proto_goTypes = nil
	file_residentorder_proto_depIdxs = nil
}
