// ID: 29001~29099

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.3
// source: guild.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EGuildPosition int32

const (
	EGuildPosition_EGUILD_POSITION_UNKNOWN     EGuildPosition = 0
	EGuildPosition_EGUILD_POSITION_LEADER      EGuildPosition = 1
	EGuildPosition_EGUILD_POSITION_VICE_LEADER EGuildPosition = 2
	EGuildPosition_EGUILD_POSITION_MEMBER      EGuildPosition = 3
)

// Enum value maps for EGuildPosition.
var (
	EGuildPosition_name = map[int32]string{
		0: "EGUILD_POSITION_UNKNOWN",
		1: "EGUILD_POSITION_LEADER",
		2: "EGUILD_POSITION_VICE_LEADER",
		3: "EGUILD_POSITION_MEMBER",
	}
	EGuildPosition_value = map[string]int32{
		"EGUILD_POSITION_UNKNOWN":     0,
		"EGUILD_POSITION_LEADER":      1,
		"EGUILD_POSITION_VICE_LEADER": 2,
		"EGUILD_POSITION_MEMBER":      3,
	}
)

func (x EGuildPosition) Enum() *EGuildPosition {
	p := new(EGuildPosition)
	*p = x
	return p
}

func (x EGuildPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EGuildPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_guild_proto_enumTypes[0].Descriptor()
}

func (EGuildPosition) Type() protoreflect.EnumType {
	return &file_guild_proto_enumTypes[0]
}

func (x EGuildPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EGuildPosition.Descriptor instead.
func (EGuildPosition) EnumDescriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{0}
}

type PGuildBasic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Declaration   string                 `protobuf:"bytes,5,opt,name=declaration,proto3" json:"declaration,omitempty"`
	Announcement  string                 `protobuf:"bytes,6,opt,name=announcement,proto3" json:"announcement,omitempty"`
	NeedApproval  bool                   `protobuf:"varint,7,opt,name=need_approval,json=needApproval,proto3" json:"need_approval,omitempty"`
	MemberCount   int32                  `protobuf:"varint,8,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	MemberLimit   int32                  `protobuf:"varint,9,opt,name=member_limit,json=memberLimit,proto3" json:"member_limit,omitempty"`
	LeaderId      int64                  `protobuf:"varint,10,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGuildBasic) Reset() {
	*x = PGuildBasic{}
	mi := &file_guild_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGuildBasic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGuildBasic) ProtoMessage() {}

func (x *PGuildBasic) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGuildBasic.ProtoReflect.Descriptor instead.
func (*PGuildBasic) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{0}
}

func (x *PGuildBasic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PGuildBasic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PGuildBasic) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PGuildBasic) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PGuildBasic) GetDeclaration() string {
	if x != nil {
		return x.Declaration
	}
	return ""
}

func (x *PGuildBasic) GetAnnouncement() string {
	if x != nil {
		return x.Announcement
	}
	return ""
}

func (x *PGuildBasic) GetNeedApproval() bool {
	if x != nil {
		return x.NeedApproval
	}
	return false
}

func (x *PGuildBasic) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *PGuildBasic) GetMemberLimit() int32 {
	if x != nil {
		return x.MemberLimit
	}
	return 0
}

func (x *PGuildBasic) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *PGuildBasic) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type PGuildMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerInfo    *PRolePublic           `protobuf:"bytes,1,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	Position      EGuildPosition         `protobuf:"varint,2,opt,name=position,proto3,enum=galaxy.protocol.EGuildPosition" json:"position,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGuildMember) Reset() {
	*x = PGuildMember{}
	mi := &file_guild_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGuildMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGuildMember) ProtoMessage() {}

func (x *PGuildMember) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGuildMember.ProtoReflect.Descriptor instead.
func (*PGuildMember) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{1}
}

func (x *PGuildMember) GetPlayerInfo() *PRolePublic {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

func (x *PGuildMember) GetPosition() EGuildPosition {
	if x != nil {
		return x.Position
	}
	return EGuildPosition_EGUILD_POSITION_UNKNOWN
}

func (x *PGuildMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

type PGuildApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       int64                  `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	GuildId       int64                  `protobuf:"varint,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	PlayerInfo    *PRolePublic           `protobuf:"bytes,3,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGuildApply) Reset() {
	*x = PGuildApply{}
	mi := &file_guild_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGuildApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGuildApply) ProtoMessage() {}

func (x *PGuildApply) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGuildApply.ProtoReflect.Descriptor instead.
func (*PGuildApply) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{2}
}

func (x *PGuildApply) GetApplyId() int64 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

func (x *PGuildApply) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *PGuildApply) GetPlayerInfo() *PRolePublic {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

func (x *PGuildApply) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type PGuildLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGuildLog) Reset() {
	*x = PGuildLog{}
	mi := &file_guild_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGuildLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGuildLog) ProtoMessage() {}

func (x *PGuildLog) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGuildLog.ProtoReflect.Descriptor instead.
func (*PGuildLog) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{3}
}

func (x *PGuildLog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PGuildLog) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 申请加入公会 (29007)
type ReqGuildApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       int64                  `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 服务端填充
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGuildApply) Reset() {
	*x = ReqGuildApply{}
	mi := &file_guild_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGuildApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGuildApply) ProtoMessage() {}

func (x *ReqGuildApply) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGuildApply.ProtoReflect.Descriptor instead.
func (*ReqGuildApply) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{4}
}

func (x *ReqGuildApply) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *ReqGuildApply) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RspGuildApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspGuildApply) Reset() {
	*x = RspGuildApply{}
	mi := &file_guild_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspGuildApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGuildApply) ProtoMessage() {}

func (x *RspGuildApply) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGuildApply.ProtoReflect.Descriptor instead.
func (*RspGuildApply) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{5}
}

// 申请列表 (29011)
type ReqGuildApplyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGuildApplyList) Reset() {
	*x = ReqGuildApplyList{}
	mi := &file_guild_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGuildApplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGuildApplyList) ProtoMessage() {}

func (x *ReqGuildApplyList) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGuildApplyList.ProtoReflect.Descriptor instead.
func (*ReqGuildApplyList) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{6}
}

type RspGuildApplyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applies       []*PGuildApply         `protobuf:"bytes,1,rep,name=applies,proto3" json:"applies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspGuildApplyList) Reset() {
	*x = RspGuildApplyList{}
	mi := &file_guild_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspGuildApplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGuildApplyList) ProtoMessage() {}

func (x *RspGuildApplyList) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGuildApplyList.ProtoReflect.Descriptor instead.
func (*RspGuildApplyList) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{7}
}

func (x *RspGuildApplyList) GetApplies() []*PGuildApply {
	if x != nil {
		return x.Applies
	}
	return nil
}

// 审批加入 (29013)
type ReqGuildApproveApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyIds      []int64                `protobuf:"varint,1,rep,packed,name=apply_ids,json=applyIds,proto3" json:"apply_ids,omitempty"` // 支持批量审批
	Approve       bool                   `protobuf:"varint,2,opt,name=approve,proto3" json:"approve,omitempty"`                          // true=同意 false=拒绝
	RoleId        int64                  `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`              // 服务端填充
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGuildApproveApply) Reset() {
	*x = ReqGuildApproveApply{}
	mi := &file_guild_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGuildApproveApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGuildApproveApply) ProtoMessage() {}

func (x *ReqGuildApproveApply) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGuildApproveApply.ProtoReflect.Descriptor instead.
func (*ReqGuildApproveApply) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{8}
}

func (x *ReqGuildApproveApply) GetApplyIds() []int64 {
	if x != nil {
		return x.ApplyIds
	}
	return nil
}

func (x *ReqGuildApproveApply) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

func (x *ReqGuildApproveApply) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RspGuildApproveApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspGuildApproveApply) Reset() {
	*x = RspGuildApproveApply{}
	mi := &file_guild_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspGuildApproveApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGuildApproveApply) ProtoMessage() {}

func (x *RspGuildApproveApply) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGuildApproveApply.ProtoReflect.Descriptor instead.
func (*RspGuildApproveApply) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{9}
}

// 踢出成员 (29015)
type ReqGuildKickMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RoleId        int64                  `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 服务端填充
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGuildKickMember) Reset() {
	*x = ReqGuildKickMember{}
	mi := &file_guild_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGuildKickMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGuildKickMember) ProtoMessage() {}

func (x *ReqGuildKickMember) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGuildKickMember.ProtoReflect.Descriptor instead.
func (*ReqGuildKickMember) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{10}
}

func (x *ReqGuildKickMember) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ReqGuildKickMember) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReqGuildKickMember) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RspGuildKickMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspGuildKickMember) Reset() {
	*x = RspGuildKickMember{}
	mi := &file_guild_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspGuildKickMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGuildKickMember) ProtoMessage() {}

func (x *RspGuildKickMember) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGuildKickMember.ProtoReflect.Descriptor instead.
func (*RspGuildKickMember) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{11}
}

// 退出公会 (29017)
type ReqGuildLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 服务端填充
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGuildLeave) Reset() {
	*x = ReqGuildLeave{}
	mi := &file_guild_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGuildLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGuildLeave) ProtoMessage() {}

func (x *ReqGuildLeave) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGuildLeave.ProtoReflect.Descriptor instead.
func (*ReqGuildLeave) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{12}
}

func (x *ReqGuildLeave) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RspGuildLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspGuildLeave) Reset() {
	*x = RspGuildLeave{}
	mi := &file_guild_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspGuildLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGuildLeave) ProtoMessage() {}

func (x *RspGuildLeave) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGuildLeave.ProtoReflect.Descriptor instead.
func (*RspGuildLeave) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{13}
}

// 解散公会 (29029)
type ReqGuildDisband struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 服务端填充
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGuildDisband) Reset() {
	*x = ReqGuildDisband{}
	mi := &file_guild_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGuildDisband) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGuildDisband) ProtoMessage() {}

func (x *ReqGuildDisband) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGuildDisband.ProtoReflect.Descriptor instead.
func (*ReqGuildDisband) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{14}
}

func (x *ReqGuildDisband) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RspGuildDisband struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspGuildDisband) Reset() {
	*x = RspGuildDisband{}
	mi := &file_guild_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspGuildDisband) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGuildDisband) ProtoMessage() {}

func (x *RspGuildDisband) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGuildDisband.ProtoReflect.Descriptor instead.
func (*RspGuildDisband) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{15}
}

// 任命/取消副会长 (29019)
type ReqGuildSetPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`           // 目标职位，参考 EGuildPosition
	RoleId        int64                  `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 服务端填充
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGuildSetPosition) Reset() {
	*x = ReqGuildSetPosition{}
	mi := &file_guild_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGuildSetPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGuildSetPosition) ProtoMessage() {}

func (x *ReqGuildSetPosition) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGuildSetPosition.ProtoReflect.Descriptor instead.
func (*ReqGuildSetPosition) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{16}
}

func (x *ReqGuildSetPosition) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ReqGuildSetPosition) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ReqGuildSetPosition) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RspGuildSetPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspGuildSetPosition) Reset() {
	*x = RspGuildSetPosition{}
	mi := &file_guild_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspGuildSetPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGuildSetPosition) ProtoMessage() {}

func (x *RspGuildSetPosition) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGuildSetPosition.ProtoReflect.Descriptor instead.
func (*RspGuildSetPosition) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{17}
}

// 转让会长 (29021)
type ReqGuildTransferLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 服务端填充
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGuildTransferLeader) Reset() {
	*x = ReqGuildTransferLeader{}
	mi := &file_guild_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGuildTransferLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGuildTransferLeader) ProtoMessage() {}

func (x *ReqGuildTransferLeader) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGuildTransferLeader.ProtoReflect.Descriptor instead.
func (*ReqGuildTransferLeader) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{18}
}

func (x *ReqGuildTransferLeader) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ReqGuildTransferLeader) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RspGuildTransferLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspGuildTransferLeader) Reset() {
	*x = RspGuildTransferLeader{}
	mi := &file_guild_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspGuildTransferLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGuildTransferLeader) ProtoMessage() {}

func (x *RspGuildTransferLeader) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGuildTransferLeader.ProtoReflect.Descriptor instead.
func (*RspGuildTransferLeader) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{19}
}

// 修改公会信息 (29023)
type ReqGuildUpdateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Declaration   string                 `protobuf:"bytes,1,opt,name=declaration,proto3" json:"declaration,omitempty"`
	Announcement  string                 `protobuf:"bytes,2,opt,name=announcement,proto3" json:"announcement,omitempty"`
	NeedApproval  bool                   `protobuf:"varint,3,opt,name=need_approval,json=needApproval,proto3" json:"need_approval,omitempty"`
	RoleId        int64                  `protobuf:"varint,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 服务端填充
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGuildUpdateInfo) Reset() {
	*x = ReqGuildUpdateInfo{}
	mi := &file_guild_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGuildUpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGuildUpdateInfo) ProtoMessage() {}

func (x *ReqGuildUpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGuildUpdateInfo.ProtoReflect.Descriptor instead.
func (*ReqGuildUpdateInfo) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{20}
}

func (x *ReqGuildUpdateInfo) GetDeclaration() string {
	if x != nil {
		return x.Declaration
	}
	return ""
}

func (x *ReqGuildUpdateInfo) GetAnnouncement() string {
	if x != nil {
		return x.Announcement
	}
	return ""
}

func (x *ReqGuildUpdateInfo) GetNeedApproval() bool {
	if x != nil {
		return x.NeedApproval
	}
	return false
}

func (x *ReqGuildUpdateInfo) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RspGuildUpdateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspGuildUpdateInfo) Reset() {
	*x = RspGuildUpdateInfo{}
	mi := &file_guild_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspGuildUpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGuildUpdateInfo) ProtoMessage() {}

func (x *RspGuildUpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGuildUpdateInfo.ProtoReflect.Descriptor instead.
func (*RspGuildUpdateInfo) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{21}
}

// 公会大厅信息 (29025)
type ReqGuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGuildInfo) Reset() {
	*x = ReqGuildInfo{}
	mi := &file_guild_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGuildInfo) ProtoMessage() {}

func (x *ReqGuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGuildInfo.ProtoReflect.Descriptor instead.
func (*ReqGuildInfo) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{22}
}

type RspGuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guild         *PGuildBasic           `protobuf:"bytes,1,opt,name=guild,proto3" json:"guild,omitempty"`
	Members       []*PGuildMember        `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Logs          []*PGuildLog           `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspGuildInfo) Reset() {
	*x = RspGuildInfo{}
	mi := &file_guild_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspGuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGuildInfo) ProtoMessage() {}

func (x *RspGuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGuildInfo.ProtoReflect.Descriptor instead.
func (*RspGuildInfo) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{23}
}

func (x *RspGuildInfo) GetGuild() *PGuildBasic {
	if x != nil {
		return x.Guild
	}
	return nil
}

func (x *RspGuildInfo) GetMembers() []*PGuildMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RspGuildInfo) GetLogs() []*PGuildLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

// 公会日志 (29027)
type ReqGuildLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGuildLogs) Reset() {
	*x = ReqGuildLogs{}
	mi := &file_guild_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGuildLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGuildLogs) ProtoMessage() {}

func (x *ReqGuildLogs) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGuildLogs.ProtoReflect.Descriptor instead.
func (*ReqGuildLogs) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{24}
}

type RspGuildLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*PGuildLog           `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspGuildLogs) Reset() {
	*x = RspGuildLogs{}
	mi := &file_guild_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspGuildLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGuildLogs) ProtoMessage() {}

func (x *RspGuildLogs) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGuildLogs.ProtoReflect.Descriptor instead.
func (*RspGuildLogs) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{25}
}

func (x *RspGuildLogs) GetLogs() []*PGuildLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

// 创建公会 (29031, HTTP)
type ReqGuildCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Declaration   string                 `protobuf:"bytes,2,opt,name=declaration,proto3" json:"declaration,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	NeedApproval  bool                   `protobuf:"varint,4,opt,name=need_approval,json=needApproval,proto3" json:"need_approval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGuildCreate) Reset() {
	*x = ReqGuildCreate{}
	mi := &file_guild_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGuildCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGuildCreate) ProtoMessage() {}

func (x *ReqGuildCreate) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGuildCreate.ProtoReflect.Descriptor instead.
func (*ReqGuildCreate) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{26}
}

func (x *ReqGuildCreate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqGuildCreate) GetDeclaration() string {
	if x != nil {
		return x.Declaration
	}
	return ""
}

func (x *ReqGuildCreate) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ReqGuildCreate) GetNeedApproval() bool {
	if x != nil {
		return x.NeedApproval
	}
	return false
}

type RspGuildCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       int64                  `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspGuildCreate) Reset() {
	*x = RspGuildCreate{}
	mi := &file_guild_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspGuildCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGuildCreate) ProtoMessage() {}

func (x *RspGuildCreate) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGuildCreate.ProtoReflect.Descriptor instead.
func (*RspGuildCreate) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{27}
}

func (x *RspGuildCreate) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

// 搜索公会 (29033, HTTP)
type ReqGuildSearch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGuildSearch) Reset() {
	*x = ReqGuildSearch{}
	mi := &file_guild_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGuildSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGuildSearch) ProtoMessage() {}

func (x *ReqGuildSearch) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGuildSearch.ProtoReflect.Descriptor instead.
func (*ReqGuildSearch) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{28}
}

func (x *ReqGuildSearch) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type RspGuildSearch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guilds        []*PGuildBasic         `protobuf:"bytes,1,rep,name=guilds,proto3" json:"guilds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspGuildSearch) Reset() {
	*x = RspGuildSearch{}
	mi := &file_guild_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspGuildSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGuildSearch) ProtoMessage() {}

func (x *RspGuildSearch) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGuildSearch.ProtoReflect.Descriptor instead.
func (*RspGuildSearch) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{29}
}

func (x *RspGuildSearch) GetGuilds() []*PGuildBasic {
	if x != nil {
		return x.Guilds
	}
	return nil
}

// 公会内容变更（含成员列表）(29051)
type NotifyGuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guild         *PGuildBasic           `protobuf:"bytes,1,opt,name=guild,proto3" json:"guild,omitempty"`
	Self          *PGuildMember          `protobuf:"bytes,2,opt,name=self,proto3" json:"self,omitempty"`
	Members       []*PGuildMember        `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyGuildInfo) Reset() {
	*x = NotifyGuildInfo{}
	mi := &file_guild_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyGuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyGuildInfo) ProtoMessage() {}

func (x *NotifyGuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyGuildInfo.ProtoReflect.Descriptor instead.
func (*NotifyGuildInfo) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{30}
}

func (x *NotifyGuildInfo) GetGuild() *PGuildBasic {
	if x != nil {
		return x.Guild
	}
	return nil
}

func (x *NotifyGuildInfo) GetSelf() *PGuildMember {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *NotifyGuildInfo) GetMembers() []*PGuildMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// 公会基本信息变更 (29052)
type NotifyGuildBasic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guild         *PGuildBasic           `protobuf:"bytes,1,opt,name=guild,proto3" json:"guild,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyGuildBasic) Reset() {
	*x = NotifyGuildBasic{}
	mi := &file_guild_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyGuildBasic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyGuildBasic) ProtoMessage() {}

func (x *NotifyGuildBasic) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyGuildBasic.ProtoReflect.Descriptor instead.
func (*NotifyGuildBasic) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{31}
}

func (x *NotifyGuildBasic) GetGuild() *PGuildBasic {
	if x != nil {
		return x.Guild
	}
	return nil
}

// 被踢出公会 (29053)
type NotifyGuildKicked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyGuildKicked) Reset() {
	*x = NotifyGuildKicked{}
	mi := &file_guild_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyGuildKicked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyGuildKicked) ProtoMessage() {}

func (x *NotifyGuildKicked) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyGuildKicked.ProtoReflect.Descriptor instead.
func (*NotifyGuildKicked) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{32}
}

func (x *NotifyGuildKicked) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 申请列表变更 (29054)
type NotifyGuildApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applies       []*PGuildApply         `protobuf:"bytes,1,rep,name=applies,proto3" json:"applies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyGuildApply) Reset() {
	*x = NotifyGuildApply{}
	mi := &file_guild_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyGuildApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyGuildApply) ProtoMessage() {}

func (x *NotifyGuildApply) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyGuildApply.ProtoReflect.Descriptor instead.
func (*NotifyGuildApply) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{33}
}

func (x *NotifyGuildApply) GetApplies() []*PGuildApply {
	if x != nil {
		return x.Applies
	}
	return nil
}

// 无需 msg_id，走 gxyactor.Request 内部路由
type ActorCreateGuild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      int64                  `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Declaration   string                 `protobuf:"bytes,3,opt,name=declaration,proto3" json:"declaration,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	NeedApproval  bool                   `protobuf:"varint,5,opt,name=need_approval,json=needApproval,proto3" json:"need_approval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorCreateGuild) Reset() {
	*x = ActorCreateGuild{}
	mi := &file_guild_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorCreateGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorCreateGuild) ProtoMessage() {}

func (x *ActorCreateGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorCreateGuild.ProtoReflect.Descriptor instead.
func (*ActorCreateGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{34}
}

func (x *ActorCreateGuild) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *ActorCreateGuild) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActorCreateGuild) GetDeclaration() string {
	if x != nil {
		return x.Declaration
	}
	return ""
}

func (x *ActorCreateGuild) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ActorCreateGuild) GetNeedApproval() bool {
	if x != nil {
		return x.NeedApproval
	}
	return false
}

var File_guild_proto protoreflect.FileDescriptor

const file_guild_proto_rawDesc = "" +
	"\n" +
	"\vguild.proto\x12\x0fgalaxy.protocol\x1a\x11msg_options.proto\x1a\n" +
	"role.proto\"\xc8\x02\n" +
	"\vPGuildBasic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12 \n" +
	"\vdeclaration\x18\x05 \x01(\tR\vdeclaration\x12\"\n" +
	"\fannouncement\x18\x06 \x01(\tR\fannouncement\x12#\n" +
	"\rneed_approval\x18\a \x01(\bR\fneedApproval\x12!\n" +
	"\fmember_count\x18\b \x01(\x05R\vmemberCount\x12!\n" +
	"\fmember_limit\x18\t \x01(\x05R\vmemberLimit\x12\x1b\n" +
	"\tleader_id\x18\n" +
	" \x01(\x03R\bleaderId\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\"\xa7\x01\n" +
	"\fPGuildMember\x12=\n" +
	"\vplayer_info\x18\x01 \x01(\v2\x1c.galaxy.protocol.PRolePublicR\n" +
	"playerInfo\x12;\n" +
	"\bposition\x18\x02 \x01(\x0e2\x1f.galaxy.protocol.EGuildPositionR\bposition\x12\x1b\n" +
	"\tjoined_at\x18\x03 \x01(\x03R\bjoinedAt\"\xa1\x01\n" +
	"\vPGuildApply\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\x03R\aapplyId\x12\x19\n" +
	"\bguild_id\x18\x02 \x01(\x03R\aguildId\x12=\n" +
	"\vplayer_info\x18\x03 \x01(\v2\x1c.galaxy.protocol.PRolePublicR\n" +
	"playerInfo\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"D\n" +
	"\tPGuildLog\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\"K\n" +
	"\rReqGuildApply\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x03R\aguildId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId:\x06\xa8\xac\x1d\xcf\xe2\x01\"\x17\n" +
	"\rRspGuildApply:\x06\xa8\xac\x1d\xd0\xe2\x01\"\x1b\n" +
	"\x11ReqGuildApplyList:\x06\xa8\xac\x1d\xd3\xe2\x01\"S\n" +
	"\x11RspGuildApplyList\x126\n" +
	"\aapplies\x18\x01 \x03(\v2\x1c.galaxy.protocol.PGuildApplyR\aapplies:\x06\xa8\xac\x1d\xd4\xe2\x01\"n\n" +
	"\x14ReqGuildApproveApply\x12\x1b\n" +
	"\tapply_ids\x18\x01 \x03(\x03R\bapplyIds\x12\x18\n" +
	"\aapprove\x18\x02 \x01(\bR\aapprove\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\x03R\x06roleId:\x06\xa8\xac\x1d\xd5\xe2\x01\"\x1e\n" +
	"\x14RspGuildApproveApply:\x06\xa8\xac\x1d\xd6\xe2\x01\"j\n" +
	"\x12ReqGuildKickMember\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\x03R\x06roleId:\x06\xa8\xac\x1d\xd7\xe2\x01\"\x1c\n" +
	"\x12RspGuildKickMember:\x06\xa8\xac\x1d\xd8\xe2\x01\"0\n" +
	"\rReqGuildLeave\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId:\x06\xa8\xac\x1d\xd9\xe2\x01\"\x17\n" +
	"\rRspGuildLeave:\x06\xa8\xac\x1d\xda\xe2\x01\"2\n" +
	"\x0fReqGuildDisband\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId:\x06\xa8\xac\x1d\xe5\xe2\x01\"\x19\n" +
	"\x0fRspGuildDisband:\x06\xa8\xac\x1d\xe6\xe2\x01\"o\n" +
	"\x13ReqGuildSetPosition\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\x03R\x06roleId:\x06\xa8\xac\x1d\xdb\xe2\x01\"\x1d\n" +
	"\x13RspGuildSetPosition:\x06\xa8\xac\x1d\xdc\xe2\x01\"V\n" +
	"\x16ReqGuildTransferLeader\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId:\x06\xa8\xac\x1d\xdd\xe2\x01\" \n" +
	"\x16RspGuildTransferLeader:\x06\xa8\xac\x1d\xde\xe2\x01\"\xa0\x01\n" +
	"\x12ReqGuildUpdateInfo\x12 \n" +
	"\vdeclaration\x18\x01 \x01(\tR\vdeclaration\x12\"\n" +
	"\fannouncement\x18\x02 \x01(\tR\fannouncement\x12#\n" +
	"\rneed_approval\x18\x03 \x01(\bR\fneedApproval\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\x03R\x06roleId:\x06\xa8\xac\x1d\xdf\xe2\x01\"\x1c\n" +
	"\x12RspGuildUpdateInfo:\x06\xa8\xac\x1d\xe0\xe2\x01\"\x16\n" +
	"\fReqGuildInfo:\x06\xa8\xac\x1d\xe1\xe2\x01\"\xb3\x01\n" +
	"\fRspGuildInfo\x122\n" +
	"\x05guild\x18\x01 \x01(\v2\x1c.galaxy.protocol.PGuildBasicR\x05guild\x127\n" +
	"\amembers\x18\x02 \x03(\v2\x1d.galaxy.protocol.PGuildMemberR\amembers\x12.\n" +
	"\x04logs\x18\x03 \x03(\v2\x1a.galaxy.protocol.PGuildLogR\x04logs:\x06\xa8\xac\x1d\xe2\xe2\x01\"\x16\n" +
	"\fReqGuildLogs:\x06\xa8\xac\x1d\xe3\xe2\x01\"F\n" +
	"\fRspGuildLogs\x12.\n" +
	"\x04logs\x18\x01 \x03(\v2\x1a.galaxy.protocol.PGuildLogR\x04logs:\x06\xa8\xac\x1d\xe4\xe2\x01\"\x87\x01\n" +
	"\x0eReqGuildCreate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdeclaration\x18\x02 \x01(\tR\vdeclaration\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12#\n" +
	"\rneed_approval\x18\x04 \x01(\bR\fneedApproval:\x06\xa8\xac\x1d\xe7\xe2\x01\"3\n" +
	"\x0eRspGuildCreate\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x03R\aguildId:\x06\xa8\xac\x1d\xe8\xe2\x01\"2\n" +
	"\x0eReqGuildSearch\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword:\x06\xa8\xac\x1d\xe9\xe2\x01\"N\n" +
	"\x0eRspGuildSearch\x124\n" +
	"\x06guilds\x18\x01 \x03(\v2\x1c.galaxy.protocol.PGuildBasicR\x06guilds:\x06\xa8\xac\x1d\xea\xe2\x01\"\xb9\x01\n" +
	"\x0fNotifyGuildInfo\x122\n" +
	"\x05guild\x18\x01 \x01(\v2\x1c.galaxy.protocol.PGuildBasicR\x05guild\x121\n" +
	"\x04self\x18\x02 \x01(\v2\x1d.galaxy.protocol.PGuildMemberR\x04self\x127\n" +
	"\amembers\x18\x03 \x03(\v2\x1d.galaxy.protocol.PGuildMemberR\amembers:\x06\xa8\xac\x1d\xfb\xe2\x01\"N\n" +
	"\x10NotifyGuildBasic\x122\n" +
	"\x05guild\x18\x01 \x01(\v2\x1c.galaxy.protocol.PGuildBasicR\x05guild:\x06\xa8\xac\x1d\xfc\xe2\x01\"3\n" +
	"\x11NotifyGuildKicked\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason:\x06\xa8\xac\x1d\xfd\xe2\x01\"R\n" +
	"\x10NotifyGuildApply\x126\n" +
	"\aapplies\x18\x01 \x03(\v2\x1c.galaxy.protocol.PGuildApplyR\aapplies:\x06\xa8\xac\x1d\xfe\xe2\x01\"\x9e\x01\n" +
	"\x10ActorCreateGuild\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\x03R\bleaderId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdeclaration\x18\x03 \x01(\tR\vdeclaration\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12#\n" +
	"\rneed_approval\x18\x05 \x01(\bR\fneedApproval*\x86\x01\n" +
	"\x0eEGuildPosition\x12\x1b\n" +
	"\x17EGUILD_POSITION_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16EGUILD_POSITION_LEADER\x10\x01\x12\x1f\n" +
	"\x1bEGUILD_POSITION_VICE_LEADER\x10\x02\x12\x1a\n" +
	"\x16EGUILD_POSITION_MEMBER\x10\x03B\tZ\a./pb;pbb\x06proto3"

var (
	file_guild_proto_rawDescOnce sync.Once
	file_guild_proto_rawDescData []byte
)

func file_guild_proto_rawDescGZIP() []byte {
	file_guild_proto_rawDescOnce.Do(func() {
		file_guild_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guild_proto_rawDesc), len(file_guild_proto_rawDesc)))
	})
	return file_guild_proto_rawDescData
}

var file_guild_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_guild_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_guild_proto_goTypes = []any{
	(EGuildPosition)(0),            // 0: galaxy.protocol.EGuildPosition
	(*PGuildBasic)(nil),            // 1: galaxy.protocol.PGuildBasic
	(*PGuildMember)(nil),           // 2: galaxy.protocol.PGuildMember
	(*PGuildApply)(nil),            // 3: galaxy.protocol.PGuildApply
	(*PGuildLog)(nil),              // 4: galaxy.protocol.PGuildLog
	(*ReqGuildApply)(nil),          // 5: galaxy.protocol.ReqGuildApply
	(*RspGuildApply)(nil),          // 6: galaxy.protocol.RspGuildApply
	(*ReqGuildApplyList)(nil),      // 7: galaxy.protocol.ReqGuildApplyList
	(*RspGuildApplyList)(nil),      // 8: galaxy.protocol.RspGuildApplyList
	(*ReqGuildApproveApply)(nil),   // 9: galaxy.protocol.ReqGuildApproveApply
	(*RspGuildApproveApply)(nil),   // 10: galaxy.protocol.RspGuildApproveApply
	(*ReqGuildKickMember)(nil),     // 11: galaxy.protocol.ReqGuildKickMember
	(*RspGuildKickMember)(nil),     // 12: galaxy.protocol.RspGuildKickMember
	(*ReqGuildLeave)(nil),          // 13: galaxy.protocol.ReqGuildLeave
	(*RspGuildLeave)(nil),          // 14: galaxy.protocol.RspGuildLeave
	(*ReqGuildDisband)(nil),        // 15: galaxy.protocol.ReqGuildDisband
	(*RspGuildDisband)(nil),        // 16: galaxy.protocol.RspGuildDisband
	(*ReqGuildSetPosition)(nil),    // 17: galaxy.protocol.ReqGuildSetPosition
	(*RspGuildSetPosition)(nil),    // 18: galaxy.protocol.RspGuildSetPosition
	(*ReqGuildTransferLeader)(nil), // 19: galaxy.protocol.ReqGuildTransferLeader
	(*RspGuildTransferLeader)(nil), // 20: galaxy.protocol.RspGuildTransferLeader
	(*ReqGuildUpdateInfo)(nil),     // 21: galaxy.protocol.ReqGuildUpdateInfo
	(*RspGuildUpdateInfo)(nil),     // 22: galaxy.protocol.RspGuildUpdateInfo
	(*ReqGuildInfo)(nil),           // 23: galaxy.protocol.ReqGuildInfo
	(*RspGuildInfo)(nil),           // 24: galaxy.protocol.RspGuildInfo
	(*ReqGuildLogs)(nil),           // 25: galaxy.protocol.ReqGuildLogs
	(*RspGuildLogs)(nil),           // 26: galaxy.protocol.RspGuildLogs
	(*ReqGuildCreate)(nil),         // 27: galaxy.protocol.ReqGuildCreate
	(*RspGuildCreate)(nil),         // 28: galaxy.protocol.RspGuildCreate
	(*ReqGuildSearch)(nil),         // 29: galaxy.protocol.ReqGuildSearch
	(*RspGuildSearch)(nil),         // 30: galaxy.protocol.RspGuildSearch
	(*NotifyGuildInfo)(nil),        // 31: galaxy.protocol.NotifyGuildInfo
	(*NotifyGuildBasic)(nil),       // 32: galaxy.protocol.NotifyGuildBasic
	(*NotifyGuildKicked)(nil),      // 33: galaxy.protocol.NotifyGuildKicked
	(*NotifyGuildApply)(nil),       // 34: galaxy.protocol.NotifyGuildApply
	(*ActorCreateGuild)(nil),       // 35: galaxy.protocol.ActorCreateGuild
	(*PRolePublic)(nil),            // 36: galaxy.protocol.PRolePublic
}
var file_guild_proto_depIdxs = []int32{
	36, // 0: galaxy.protocol.PGuildMember.player_info:type_name -> galaxy.protocol.PRolePublic
	0,  // 1: galaxy.protocol.PGuildMember.position:type_name -> galaxy.protocol.EGuildPosition
	36, // 2: galaxy.protocol.PGuildApply.player_info:type_name -> galaxy.protocol.PRolePublic
	3,  // 3: galaxy.protocol.RspGuildApplyList.applies:type_name -> galaxy.protocol.PGuildApply
	1,  // 4: galaxy.protocol.RspGuildInfo.guild:type_name -> galaxy.protocol.PGuildBasic
	2,  // 5: galaxy.protocol.RspGuildInfo.members:type_name -> galaxy.protocol.PGuildMember
	4,  // 6: galaxy.protocol.RspGuildInfo.logs:type_name -> galaxy.protocol.PGuildLog
	4,  // 7: galaxy.protocol.RspGuildLogs.logs:type_name -> galaxy.protocol.PGuildLog
	1,  // 8: galaxy.protocol.RspGuildSearch.guilds:type_name -> galaxy.protocol.PGuildBasic
	1,  // 9: galaxy.protocol.NotifyGuildInfo.guild:type_name -> galaxy.protocol.PGuildBasic
	2,  // 10: galaxy.protocol.NotifyGuildInfo.self:type_name -> galaxy.protocol.PGuildMember
	2,  // 11: galaxy.protocol.NotifyGuildInfo.members:type_name -> galaxy.protocol.PGuildMember
	1,  // 12: galaxy.protocol.NotifyGuildBasic.guild:type_name -> galaxy.protocol.PGuildBasic
	3,  // 13: galaxy.protocol.NotifyGuildApply.applies:type_name -> galaxy.protocol.PGuildApply
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_guild_proto_init() }
func file_guild_proto_init() {
	if File_guild_proto != nil {
		return
	}
	file_msg_options_proto_init()
	file_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guild_proto_rawDesc), len(file_guild_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guild_proto_goTypes,
		DependencyIndexes: file_guild_proto_depIdxs,
		EnumInfos:         file_guild_proto_enumTypes,
		MessageInfos:      file_guild_proto_msgTypes,
	}.Build()
	File_guild_proto = out.File
	file_guild_proto_goTypes = nil
	file_guild_proto_depIdxs = nil
}
