
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;

type GardenEItemQuality int32
const (
    /**
     * 普通
     */
    GardenEItemQuality_NORMAL GardenEItemQuality = 1;
    /**
     * 良品
     */
    GardenEItemQuality_FINE GardenEItemQuality = 2;
    /**
     * 稀有
     */
    GardenEItemQuality_RARE GardenEItemQuality = 3;
    /**
     * 史诗
     */
    GardenEItemQuality_EPIC GardenEItemQuality = 4;
    /**
     * 传说
     */
    GardenEItemQuality_LEGENDARY GardenEItemQuality = 5;
)

