
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


import "errors"

type GardenMainTask struct {
    Id int32
    Chapter int32
    Sort int32
    Name string
    Desc string
    PreTaskId int32
    ProgressMode GardenETaskProgressMode
    TargetType GardenETaskTargetType
    TargetParam int32
    TargetNum int32
    Reward []*GardenGoodStack
}

const TypeId_GardenMainTask = 1367164567

func (*GardenMainTask) GetTypeId() int32 {
    return 1367164567
}

func NewGardenMainTask(_buf map[string]interface{}) (_v *GardenMainTask, err error) {
    _v = &GardenMainTask{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_chapter__ interface{}; if __json_chapter__, _ok_ = _buf["chapter"]; !_ok_ || __json_chapter__ == nil { err = errors.New("chapter error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_chapter__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Chapter = __x__ }}
    { var _ok_ bool; var __json_sort__ interface{}; if __json_sort__, _ok_ = _buf["sort"]; !_ok_ || __json_sort__ == nil { err = errors.New("sort error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_sort__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Sort = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_desc__ interface{}; if __json_desc__, _ok_ = _buf["desc"]; !_ok_ || __json_desc__ == nil { err = errors.New("desc error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_desc__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc = __x__ }}
    { var _ok_ bool; var __json_pre_task_id__ interface{}; if __json_pre_task_id__, _ok_ = _buf["pre_task_id"]; !_ok_ || __json_pre_task_id__ == nil { err = errors.New("pre_task_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_pre_task_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.PreTaskId = __x__ }}
    { var _ok_ bool; var __json_progress_mode__ interface{}; if __json_progress_mode__, _ok_ = _buf["progress_mode"]; !_ok_ || __json_progress_mode__ == nil { err = errors.New("progress_mode error"); return } else { var __x__ GardenETaskProgressMode;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_progress_mode__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = GardenETaskProgressMode(_x_) }; _v.ProgressMode = __x__ }}
    { var _ok_ bool; var __json_target_type__ interface{}; if __json_target_type__, _ok_ = _buf["target_type"]; !_ok_ || __json_target_type__ == nil { err = errors.New("target_type error"); return } else { var __x__ GardenETaskTargetType;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_target_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = GardenETaskTargetType(_x_) }; _v.TargetType = __x__ }}
    { var _ok_ bool; var __json_target_param__ interface{}; if __json_target_param__, _ok_ = _buf["target_param"]; !_ok_ || __json_target_param__ == nil { err = errors.New("target_param error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_target_param__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TargetParam = __x__ }}
    { var _ok_ bool; var __json_target_num__ interface{}; if __json_target_num__, _ok_ = _buf["target_num"]; !_ok_ || __json_target_num__ == nil { err = errors.New("target_num error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_target_num__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TargetNum = __x__ }}
    { var _ok_ bool; var __json_reward__ interface{}; if __json_reward__, _ok_ = _buf["reward"]; !_ok_ || __json_reward__ == nil { err = errors.New("reward error"); return } else { var __x__ []*GardenGoodStack;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_reward__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*GardenGoodStack, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *GardenGoodStack
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewGardenGoodStack(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Reward = __x__ }}
    return
}

