
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


import "errors"

type GardenResidentOrderProgressReward struct {
    Id int32
    NeedCount int32
    Reward []*GardenGoodStack
    Icon string
}

const TypeId_GardenResidentOrderProgressReward = 2030478049

func (*GardenResidentOrderProgressReward) GetTypeId() int32 {
    return 2030478049
}

func NewGardenResidentOrderProgressReward(_buf map[string]interface{}) (_v *GardenResidentOrderProgressReward, err error) {
    _v = &GardenResidentOrderProgressReward{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_need_count__ interface{}; if __json_need_count__, _ok_ = _buf["need_count"]; !_ok_ || __json_need_count__ == nil { err = errors.New("need_count error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_need_count__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.NeedCount = __x__ }}
    { var _ok_ bool; var __json_reward__ interface{}; if __json_reward__, _ok_ = _buf["reward"]; !_ok_ || __json_reward__ == nil { err = errors.New("reward error"); return } else { var __x__ []*GardenGoodStack;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_reward__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*GardenGoodStack, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *GardenGoodStack
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewGardenGoodStack(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Reward = __x__ }}
    { var _ok_ bool; var __json_icon__ interface{}; if __json_icon__, _ok_ = _buf["icon"]; !_ok_ || __json_icon__ == nil { err = errors.New("icon error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_icon__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Icon = __x__ }}
    return
}

