
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


type GardenTbResidentOrder struct {
    _dataMap map[int32]*GardenResidentOrder
    _dataList []*GardenResidentOrder
}

func NewGardenTbResidentOrder(_buf []map[string]interface{}) (*GardenTbResidentOrder, error) {
    _dataList := make([]*GardenResidentOrder, 0, len(_buf))
    dataMap := make(map[int32]*GardenResidentOrder)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGardenResidentOrder(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GardenTbResidentOrder{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GardenTbResidentOrder) GetDataMap() map[int32]*GardenResidentOrder {
    return table._dataMap
}

func (table *GardenTbResidentOrder) GetDataList() []*GardenResidentOrder {
    return table._dataList
}

func (table *GardenTbResidentOrder) Get(key int32) *GardenResidentOrder {
    return table._dataMap[key]
}


