
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;

type GardenEItemUseType int32
const (
    /**
     * 不可使用
     */
    GardenEItemUseType_NONE GardenEItemUseType = 0;
    /**
     * 开启宝箱
     */
    GardenEItemUseType_OPEN_CHEST GardenEItemUseType = 1;
    /**
     * 获得经验
     */
    GardenEItemUseType_ADD_EXP GardenEItemUseType = 2;
    /**
     * 恢复水滴
     */
    GardenEItemUseType_ADD_ENERGY GardenEItemUseType = 3;
    /**
     * 获得增益
     */
    GardenEItemUseType_ADD_BUFF GardenEItemUseType = 4;
)

