
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


type GardenTbItem struct {
    _dataMap map[int32]*GardenItem
    _dataList []*GardenItem
}

func NewGardenTbItem(_buf []map[string]interface{}) (*GardenTbItem, error) {
    _dataList := make([]*GardenItem, 0, len(_buf))
    dataMap := make(map[int32]*GardenItem)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGardenItem(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GardenTbItem{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GardenTbItem) GetDataMap() map[int32]*GardenItem {
    return table._dataMap
}

func (table *GardenTbItem) GetDataList() []*GardenItem {
    return table._dataList
}

func (table *GardenTbItem) Get(key int32) *GardenItem {
    return table._dataMap[key]
}


