
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


import "errors"

type GardenFriendConfig struct {
    UnlockLevel int32
    FriendMaxCount int32
    ApplySendLimit int32
    ApplyReceiveLimit int32
    ApplyExpireSeconds int32
    DeleteReapplyCdSeconds int32
    SearchResultLimit int32
}

const TypeId_GardenFriendConfig = 2126193337

func (*GardenFriendConfig) GetTypeId() int32 {
    return 2126193337
}

func NewGardenFriendConfig(_buf map[string]interface{}) (_v *GardenFriendConfig, err error) {
    _v = &GardenFriendConfig{}
    { var _ok_ bool; var __json_unlock_level__ interface{}; if __json_unlock_level__, _ok_ = _buf["unlock_level"]; !_ok_ || __json_unlock_level__ == nil { err = errors.New("unlock_level error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_unlock_level__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UnlockLevel = __x__ }}
    { var _ok_ bool; var __json_friend_max_count__ interface{}; if __json_friend_max_count__, _ok_ = _buf["friend_max_count"]; !_ok_ || __json_friend_max_count__ == nil { err = errors.New("friend_max_count error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_friend_max_count__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.FriendMaxCount = __x__ }}
    { var _ok_ bool; var __json_apply_send_limit__ interface{}; if __json_apply_send_limit__, _ok_ = _buf["apply_send_limit"]; !_ok_ || __json_apply_send_limit__ == nil { err = errors.New("apply_send_limit error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_apply_send_limit__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ApplySendLimit = __x__ }}
    { var _ok_ bool; var __json_apply_receive_limit__ interface{}; if __json_apply_receive_limit__, _ok_ = _buf["apply_receive_limit"]; !_ok_ || __json_apply_receive_limit__ == nil { err = errors.New("apply_receive_limit error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_apply_receive_limit__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ApplyReceiveLimit = __x__ }}
    { var _ok_ bool; var __json_apply_expire_seconds__ interface{}; if __json_apply_expire_seconds__, _ok_ = _buf["apply_expire_seconds"]; !_ok_ || __json_apply_expire_seconds__ == nil { err = errors.New("apply_expire_seconds error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_apply_expire_seconds__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ApplyExpireSeconds = __x__ }}
    { var _ok_ bool; var __json_delete_reapply_cd_seconds__ interface{}; if __json_delete_reapply_cd_seconds__, _ok_ = _buf["delete_reapply_cd_seconds"]; !_ok_ || __json_delete_reapply_cd_seconds__ == nil { err = errors.New("delete_reapply_cd_seconds error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_delete_reapply_cd_seconds__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.DeleteReapplyCdSeconds = __x__ }}
    { var _ok_ bool; var __json_search_result_limit__ interface{}; if __json_search_result_limit__, _ok_ = _buf["search_result_limit"]; !_ok_ || __json_search_result_limit__ == nil { err = errors.New("search_result_limit error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_search_result_limit__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SearchResultLimit = __x__ }}
    return
}

