
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


type GardenTbFlower struct {
    _dataMap map[int32]*GardenFlower
    _dataList []*GardenFlower
}

func NewGardenTbFlower(_buf []map[string]interface{}) (*GardenTbFlower, error) {
    _dataList := make([]*GardenFlower, 0, len(_buf))
    dataMap := make(map[int32]*GardenFlower)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGardenFlower(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GardenTbFlower{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GardenTbFlower) GetDataMap() map[int32]*GardenFlower {
    return table._dataMap
}

func (table *GardenTbFlower) GetDataList() []*GardenFlower {
    return table._dataList
}

func (table *GardenTbFlower) Get(key int32) *GardenFlower {
    return table._dataMap[key]
}


