
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


import "errors"

type GardenGuildPosition struct {
    Id int32
    Name string
    CanApprove bool
    CanEditNotice bool
    CanKick bool
    CanAppointVice bool
    CanTransferLeader bool
    CanDisband bool
}

const TypeId_GardenGuildPosition = 1109714467

func (*GardenGuildPosition) GetTypeId() int32 {
    return 1109714467
}

func NewGardenGuildPosition(_buf map[string]interface{}) (_v *GardenGuildPosition, err error) {
    _v = &GardenGuildPosition{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_can_approve__ interface{}; if __json_can_approve__, _ok_ = _buf["can_approve"]; !_ok_ || __json_can_approve__ == nil { err = errors.New("can_approve error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_can_approve__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanApprove = __x__ }}
    { var _ok_ bool; var __json_can_edit_notice__ interface{}; if __json_can_edit_notice__, _ok_ = _buf["can_edit_notice"]; !_ok_ || __json_can_edit_notice__ == nil { err = errors.New("can_edit_notice error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_can_edit_notice__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanEditNotice = __x__ }}
    { var _ok_ bool; var __json_can_kick__ interface{}; if __json_can_kick__, _ok_ = _buf["can_kick"]; !_ok_ || __json_can_kick__ == nil { err = errors.New("can_kick error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_can_kick__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanKick = __x__ }}
    { var _ok_ bool; var __json_can_appoint_vice__ interface{}; if __json_can_appoint_vice__, _ok_ = _buf["can_appoint_vice"]; !_ok_ || __json_can_appoint_vice__ == nil { err = errors.New("can_appoint_vice error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_can_appoint_vice__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanAppointVice = __x__ }}
    { var _ok_ bool; var __json_can_transfer_leader__ interface{}; if __json_can_transfer_leader__, _ok_ = _buf["can_transfer_leader"]; !_ok_ || __json_can_transfer_leader__ == nil { err = errors.New("can_transfer_leader error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_can_transfer_leader__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanTransferLeader = __x__ }}
    { var _ok_ bool; var __json_can_disband__ interface{}; if __json_can_disband__, _ok_ = _buf["can_disband"]; !_ok_ || __json_can_disband__ == nil { err = errors.New("can_disband error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_can_disband__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanDisband = __x__ }}
    return
}

