
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gametable;


import "errors"

type GlobalGlobal struct {
    MaxGrid int32
    FriendGiftCost []*ItemItemRC
}

const TypeId_GlobalGlobal = 1250542702

func (*GlobalGlobal) GetTypeId() int32 {
    return 1250542702
}

func NewGlobalGlobal(_buf map[string]interface{}) (_v *GlobalGlobal, err error) {
    _v = &GlobalGlobal{}
    { var _ok_ bool; var __json_max_grid__ interface{}; if __json_max_grid__, _ok_ = _buf["max_grid"]; !_ok_ || __json_max_grid__ == nil { err = errors.New("max_grid error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_max_grid__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.MaxGrid = __x__ }}
    { var _ok_ bool; var __json_friend_gift_cost__ interface{}; if __json_friend_gift_cost__, _ok_ = _buf["friend_gift_cost"]; !_ok_ || __json_friend_gift_cost__ == nil { err = errors.New("friend_gift_cost error"); return } else { var __x__ []*ItemItemRC;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_friend_gift_cost__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*ItemItemRC, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *ItemItemRC
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewItemItemRC(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.FriendGiftCost = __x__ }}
    return
}

