
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gametable;


type SignTbSignPatch struct {
    _dataMap map[int32]*SignsignPatch
    _dataList []*SignsignPatch
}

func NewSignTbSignPatch(_buf []map[string]interface{}) (*SignTbSignPatch, error) {
    _dataList := make([]*SignsignPatch, 0, len(_buf))
    dataMap := make(map[int32]*SignsignPatch)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSignsignPatch(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SignTbSignPatch{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SignTbSignPatch) GetDataMap() map[int32]*SignsignPatch {
    return table._dataMap
}

func (table *SignTbSignPatch) GetDataList() []*SignsignPatch {
    return table._dataList
}

func (table *SignTbSignPatch) Get(key int32) *SignsignPatch {
    return table._dataMap[key]
}


