[node]
    name = "game"
    host = "127.0.0.1"
	apps = ["guild"]
[postgres]
	url = "postgresql://postgres:%40zyc0131@127.0.0.1:5432/postgres?sslmode=disable"
[redis]
	addr = "localhost:6379"
	password = "@zyc0131"
	db = 0
	dial_timeout = "5s"
[log]
	path = "./log"
	level = "all"
	file = "{Y-m-d}.log"
	stStatus = 0
[registery]
	type = "consul"
[registery.consul]
	address = "localhost:8500"
	ttl = "10s"
	refresh_ttl = "10s"
