
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


import "errors"

type GardenGlobalConfig struct {
    InitItems []*GardenGoodStack
    MaxEnergy int32
    EnergyRecoverSec int32
    BagMaxCells int32
}

const TypeId_GardenGlobalConfig = 1723761662

func (*GardenGlobalConfig) GetTypeId() int32 {
    return 1723761662
}

func NewGardenGlobalConfig(_buf map[string]interface{}) (_v *GardenGlobalConfig, err error) {
    _v = &GardenGlobalConfig{}
    { var _ok_ bool; var __json_init_items__ interface{}; if __json_init_items__, _ok_ = _buf["init_items"]; !_ok_ || __json_init_items__ == nil { err = errors.New("init_items error"); return } else { var __x__ []*GardenGoodStack;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_init_items__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*GardenGoodStack, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *GardenGoodStack
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewGardenGoodStack(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.InitItems = __x__ }}
    { var _ok_ bool; var __json_max_energy__ interface{}; if __json_max_energy__, _ok_ = _buf["max_energy"]; !_ok_ || __json_max_energy__ == nil { err = errors.New("max_energy error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_max_energy__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.MaxEnergy = __x__ }}
    { var _ok_ bool; var __json_energy_recover_sec__ interface{}; if __json_energy_recover_sec__, _ok_ = _buf["energy_recover_sec"]; !_ok_ || __json_energy_recover_sec__ == nil { err = errors.New("energy_recover_sec error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_energy_recover_sec__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.EnergyRecoverSec = __x__ }}
    { var _ok_ bool; var __json_bag_max_cells__ interface{}; if __json_bag_max_cells__, _ok_ = _buf["bag_max_cells"]; !_ok_ || __json_bag_max_cells__ == nil { err = errors.New("bag_max_cells error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_bag_max_cells__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.BagMaxCells = __x__ }}
    return
}

