
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


type GardenTbFlowerBreak struct {
    _dataMap map[int32]*GardenFlowerBreak
    _dataList []*GardenFlowerBreak
}

func NewGardenTbFlowerBreak(_buf []map[string]interface{}) (*GardenTbFlowerBreak, error) {
    _dataList := make([]*GardenFlowerBreak, 0, len(_buf))
    dataMap := make(map[int32]*GardenFlowerBreak)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGardenFlowerBreak(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GardenTbFlowerBreak{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GardenTbFlowerBreak) GetDataMap() map[int32]*GardenFlowerBreak {
    return table._dataMap
}

func (table *GardenTbFlowerBreak) GetDataList() []*GardenFlowerBreak {
    return table._dataList
}

func (table *GardenTbFlowerBreak) Get(key int32) *GardenFlowerBreak {
    return table._dataMap[key]
}


