
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


type GardenTbGardenPlot struct {
    _dataMap map[int32]*GardenPlot
    _dataList []*GardenPlot
}

func NewGardenTbGardenPlot(_buf []map[string]interface{}) (*GardenTbGardenPlot, error) {
    _dataList := make([]*GardenPlot, 0, len(_buf))
    dataMap := make(map[int32]*GardenPlot)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGardenPlot(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GardenTbGardenPlot{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GardenTbGardenPlot) GetDataMap() map[int32]*GardenPlot {
    return table._dataMap
}

func (table *GardenTbGardenPlot) GetDataList() []*GardenPlot {
    return table._dataList
}

func (table *GardenTbGardenPlot) Get(key int32) *GardenPlot {
    return table._dataMap[key]
}
