
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


type GardenTbGlobalConfig struct {
    _dataMap map[string]*GardenGlobalConfig
    _dataList []*GardenGlobalConfig
}

func NewGardenTbGlobalConfig(_buf []map[string]interface{}) (*GardenTbGlobalConfig, error) {
    _dataList := make([]*GardenGlobalConfig, 0, len(_buf))
    dataMap := make(map[string]*GardenGlobalConfig)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGardenGlobalConfig(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Name] = _v
        }
    }
    return &GardenTbGlobalConfig{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GardenTbGlobalConfig) GetDataMap() map[string]*GardenGlobalConfig {
    return table._dataMap
}

func (table *GardenTbGlobalConfig) GetDataList() []*GardenGlobalConfig {
    return table._dataList
}

func (table *GardenTbGlobalConfig) Get(key string) *GardenGlobalConfig {
    return table._dataMap[key]
}


