
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;

type GardenETaskTargetType int32
const (
    /**
     * 开始培育
     */
    GardenETaskTargetType_BREED_START GardenETaskTargetType = 1;
    /**
     * 领取培育完成
     */
    GardenETaskTargetType_BREED_FINISH GardenETaskTargetType = 2;
    /**
     * 种植鲜花
     */
    GardenETaskTargetType_PLANT_FLOWER GardenETaskTargetType = 3;
    /**
     * 浇水
     */
    GardenETaskTargetType_WATER_FLOWER GardenETaskTargetType = 4;
    /**
     * 收获鲜花
     */
    GardenETaskTargetType_HARVEST_FLOWER GardenETaskTargetType = 5;
    /**
     * 获得物品
     */
    GardenETaskTargetType_GET_ITEM GardenETaskTargetType = 6;
    /**
     * 玩家等级达到
     */
    GardenETaskTargetType_PLAYER_LEVEL GardenETaskTargetType = 7;
    /**
     * 解锁地块
     */
    GardenETaskTargetType_UNLOCK_PLOT GardenETaskTargetType = 8;
    /**
     * 鲜花等级达到
     */
    GardenETaskTargetType_FLOWER_LEVEL GardenETaskTargetType = 9;
    /**
     * 拥有物品
     */
    GardenETaskTargetType_OWN_ITEM GardenETaskTargetType = 10;
)

