
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


import "errors"

type GardenGuildLevel struct {
    Level int32
    MemberLimit int32
    ViceLeaderLimit int32
}

const TypeId_GardenGuildLevel = 1933115594

func (*GardenGuildLevel) GetTypeId() int32 {
    return 1933115594
}

func NewGardenGuildLevel(_buf map[string]interface{}) (_v *GardenGuildLevel, err error) {
    _v = &GardenGuildLevel{}
    { var _ok_ bool; var __json_level__ interface{}; if __json_level__, _ok_ = _buf["level"]; !_ok_ || __json_level__ == nil { err = errors.New("level error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_level__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Level = __x__ }}
    { var _ok_ bool; var __json_member_limit__ interface{}; if __json_member_limit__, _ok_ = _buf["member_limit"]; !_ok_ || __json_member_limit__ == nil { err = errors.New("member_limit error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_member_limit__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.MemberLimit = __x__ }}
    { var _ok_ bool; var __json_vice_leader_limit__ interface{}; if __json_vice_leader_limit__, _ok_ = _buf["vice_leader_limit"]; !_ok_ || __json_vice_leader_limit__ == nil { err = errors.New("vice_leader_limit error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_vice_leader_limit__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ViceLeaderLimit = __x__ }}
    return
}

