
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


import "errors"

type GardenResident struct {
    Id int32
    Name string
    Avatar string
    Portrait string
    OrderText string
}

const TypeId_GardenResident = 1028483337

func (*GardenResident) GetTypeId() int32 {
    return 1028483337
}

func NewGardenResident(_buf map[string]interface{}) (_v *GardenResident, err error) {
    _v = &GardenResident{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_avatar__ interface{}; if __json_avatar__, _ok_ = _buf["avatar"]; !_ok_ || __json_avatar__ == nil { err = errors.New("avatar error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_avatar__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Avatar = __x__ }}
    { var _ok_ bool; var __json_portrait__ interface{}; if __json_portrait__, _ok_ = _buf["portrait"]; !_ok_ || __json_portrait__ == nil { err = errors.New("portrait error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_portrait__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Portrait = __x__ }}
    { var _ok_ bool; var __json_order_text__ interface{}; if __json_order_text__, _ok_ = _buf["order_text"]; !_ok_ || __json_order_text__ == nil { err = errors.New("order_text error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_order_text__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.OrderText = __x__ }}
    return
}

