
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


type GardenTbGuildChat struct {
    _dataMap map[int32]*GardenGuildChat
    _dataList []*GardenGuildChat
}

func NewGardenTbGuildChat(_buf []map[string]interface{}) (*GardenTbGuildChat, error) {
    _dataList := make([]*GardenGuildChat, 0, len(_buf))
    dataMap := make(map[int32]*GardenGuildChat)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGardenGuildChat(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GardenTbGuildChat{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GardenTbGuildChat) GetDataMap() map[int32]*GardenGuildChat {
    return table._dataMap
}

func (table *GardenTbGuildChat) GetDataList() []*GardenGuildChat {
    return table._dataList
}

func (table *GardenTbGuildChat) Get(key int32) *GardenGuildChat {
    return table._dataMap[key]
}


