
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;



import "errors"

type GardenTbGlobalConfig struct {
    _data *GardenGlobalConfig
}

func NewGardenTbGlobalConfig(_buf []map[string]interface{}) (*GardenTbGlobalConfig, error) {
	if len(_buf) != 1 {
        return nil, errors.New(" size != 1 ")
	} else {
		if _v, err2 := NewGardenGlobalConfig(_buf[0]); err2 != nil {
			return nil, err2
		} else {
		    return &GardenTbGlobalConfig{_data:_v}, nil
		}
	}
}

func (table *GardenTbGlobalConfig) Get() *GardenGlobalConfig {
    return table._data
}


