
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;


import "errors"

type GardenGuildConfig struct {
    Id int32
    UnlockLevel int32
    CreateCost []*GardenGoodStack
    NameLimit int32
    DeclarationLimit int32
    AnnouncementLimit int32
    ApplyExpireHours int32
    DefaultNeedApproval bool
    DefaultIcon string
}

const TypeId_GardenGuildConfig = -451623236

func (*GardenGuildConfig) GetTypeId() int32 {
    return -451623236
}

func NewGardenGuildConfig(_buf map[string]interface{}) (_v *GardenGuildConfig, err error) {
    _v = &GardenGuildConfig{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_unlock_level__ interface{}; if __json_unlock_level__, _ok_ = _buf["unlock_level"]; !_ok_ || __json_unlock_level__ == nil { err = errors.New("unlock_level error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_unlock_level__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UnlockLevel = __x__ }}
    { var _ok_ bool; var __json_create_cost__ interface{}; if __json_create_cost__, _ok_ = _buf["create_cost"]; !_ok_ || __json_create_cost__ == nil { err = errors.New("create_cost error"); return } else { var __x__ []*GardenGoodStack;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_create_cost__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*GardenGoodStack, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *GardenGoodStack
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewGardenGoodStack(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.CreateCost = __x__ }}
    { var _ok_ bool; var __json_name_limit__ interface{}; if __json_name_limit__, _ok_ = _buf["name_limit"]; !_ok_ || __json_name_limit__ == nil { err = errors.New("name_limit error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_name_limit__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.NameLimit = __x__ }}
    { var _ok_ bool; var __json_declaration_limit__ interface{}; if __json_declaration_limit__, _ok_ = _buf["declaration_limit"]; !_ok_ || __json_declaration_limit__ == nil { err = errors.New("declaration_limit error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_declaration_limit__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.DeclarationLimit = __x__ }}
    { var _ok_ bool; var __json_announcement_limit__ interface{}; if __json_announcement_limit__, _ok_ = _buf["announcement_limit"]; !_ok_ || __json_announcement_limit__ == nil { err = errors.New("announcement_limit error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_announcement_limit__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.AnnouncementLimit = __x__ }}
    { var _ok_ bool; var __json_apply_expire_hours__ interface{}; if __json_apply_expire_hours__, _ok_ = _buf["apply_expire_hours"]; !_ok_ || __json_apply_expire_hours__ == nil { err = errors.New("apply_expire_hours error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_apply_expire_hours__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ApplyExpireHours = __x__ }}
    { var _ok_ bool; var __json_default_need_approval__ interface{}; if __json_default_need_approval__, _ok_ = _buf["default_need_approval"]; !_ok_ || __json_default_need_approval__ == nil { err = errors.New("default_need_approval error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_default_need_approval__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.DefaultNeedApproval = __x__ }}
    { var _ok_ bool; var __json_default_icon__ interface{}; if __json_default_icon__, _ok_ = _buf["default_icon"]; !_ok_ || __json_default_icon__ == nil { err = errors.New("default_icon error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_default_icon__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.DefaultIcon = __x__ }}
    return
}

