
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gamecfg;

type JsonLoader func(string) ([]map[string]interface{}, error)

type Tables struct {
    TbItem *GardenTbItem
    TbItemTag *GardenTbItemTag
    TbGlobalConfig *GardenTbGlobalConfig
}

func NewTables(loader JsonLoader) (*Tables, error) {
    var err error
    var buf []map[string]interface{}

    tables := &Tables{}
    if buf, err = loader("garden_tbitem") ; err != nil {
        return nil, err
    }
    if tables.TbItem, err = NewGardenTbItem(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("garden_tbitemtag") ; err != nil {
        return nil, err
    }
    if tables.TbItemTag, err = NewGardenTbItemTag(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("garden_tbglobalconfig") ; err != nil {
        return nil, err
    }
    if tables.TbGlobalConfig, err = NewGardenTbGlobalConfig(buf) ; err != nil {
        return nil, err
    }
    return tables, nil
}


