syntax = "proto3";
option go_package="./pb;pb";
package galaxy.protocol;
import "google/protobuf/any.proto";


message ActorTimerMsg {
    string name = 1;     
    int64 time = 3;
}

message ActorError {
    string reason = 1;
}

message ClientMsg {
    string id = 1;
    google.protobuf.Any msg = 2;
}

message ServerMsg {
    google.protobuf.Any msg = 1;
}

message ActorActive {
    string kind = 1;
    string id = 2;
}

message ActorStop {
    string reason = 1;
}

message ActorPid {
    string address = 1;
    string Id = 2;
}
