syntax = "proto3";
option go_package="./pb;pb";
package galaxy.protocol;

import "role.proto";

message ReqFriendInfo {

}

message PFriendInfo {
    PRolePublic role_public = 1; 
    int64 friend_time = 2;
    int32 favor = 3;
    int64 send_gift_time = 4;
    bool can_recv_gift = 5;
}

message PFriendApply {
    PRolePublic role_public = 1; 
    int64 friend_time = 2;
}

message RspFriendInfo {
    repeated PFriendInfo friends = 1; // 好友列表
    repeated PFriendApply apply = 2; // 申请列表（自己申请别人)
    repeated PFriendApply applyed = 3; // 被申请列表（别人申请自己)
}

message ReqFriendApply {
    string role_id = 1;
}

message RspFriendApply {
    PFriendApply apply_new = 1; // 申请者
}

message ReqFriendDealApply {
   string role_id = 1;
   int32 deal = 2; // 0-拒绝 1-同一
}

message RspFriendDealApply {
    PFriendInfo friend_new = 1; // 新增好友
    string applyed_delete = 2; // 删除的申请者
}

message ReqFriendDelete {
    string role_id = 1;
}

message RspFriendDelete {
    string friend_delete = 1;
}

message ReqFriendSendGift{
    string role_id = 1;
}

message RspFriendSendGift{
    int64 send_gift_time = 4;
}

message ReqFriendRecvGift{
    string role_id = 1;
}

message RspFriendRecvGift{
    int32 favor = 3;
}
