
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


type ActivityTbActivity struct {
    _dataMap map[int32]*ActivityActivity
    _dataList []*ActivityActivity
}

func NewActivityTbActivity(_buf []map[string]interface{}) (*ActivityTbActivity, error) {
    _dataList := make([]*ActivityActivity, 0, len(_buf))
    dataMap := make(map[int32]*ActivityActivity)

    for _, _ele_ := range _buf {
        if _v, err2 := NewActivityActivity(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &ActivityTbActivity{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *ActivityTbActivity) GetDataMap() map[int32]*ActivityActivity {
    return table._dataMap
}

func (table *ActivityTbActivity) GetDataList() []*ActivityActivity {
    return table._dataList
}

func (table *ActivityTbActivity) Get(key int32) *ActivityActivity {
    return table._dataMap[key]
}


