
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


import "errors"

type ControllerTimeSwitcher struct {
    Name string
    Type int32
    Param string
}

const TypeId_ControllerTimeSwitcher = 1670265344

func (*ControllerTimeSwitcher) GetTypeId() int32 {
    return 1670265344
}

func NewControllerTimeSwitcher(_buf map[string]interface{}) (_v *ControllerTimeSwitcher, err error) {
    _v = &ControllerTimeSwitcher{}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_type__ interface{}; if __json_type__, _ok_ = _buf["type"]; !_ok_ || __json_type__ == nil { err = errors.New("type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_param__ interface{}; if __json_param__, _ok_ = _buf["param"]; !_ok_ || __json_param__ == nil { err = errors.New("param error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_param__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Param = __x__ }}
    return
}

