
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;



import "errors"

type GlobalTbGlobal struct {
    _data *GlobalGlobal
}

func NewGlobalTbGlobal(_buf []map[string]interface{}) (*GlobalTbGlobal, error) {
	if len(_buf) != 1 {
        return nil, errors.New(" size != 1 ")
	} else {
		if _v, err2 := NewGlobalGlobal(_buf[0]); err2 != nil {
			return nil, err2
		} else {
		    return &GlobalTbGlobal{_data:_v}, nil
		}
	}
}

func (table *GlobalTbGlobal) Get() *GlobalGlobal {
    return table._data
}


