//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig

import "errors"

type SignsignCheckIn struct {
    Id int32
    Rewards []*ItemItemRC
    Vip int32
    Desc string
}

const TypeId_SignsignCheckIn = -594089697

func (*SignsignCheckIn) GetTypeId() int32 {
    return -594089697
}

func (_v *SignsignCheckIn)Deserialize(_buf map[string]interface{}) (err error) {
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
     {
                var _arr_ []interface{}
                var _ok_ bool
                if _arr_, _ok_ = _buf["rewards"].([]interface{}); !_ok_ { err = errors.New("rewards error"); return }

                _v.Rewards = make([]*ItemItemRC, 0, len(_arr_))
                
                for _, _e_ := range _arr_ {
                    var _list_v_ *ItemItemRC
                    { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v_ error"); return }; if _list_v_, err = DeserializeItemItemRC(_x_); err != nil { return } }
                    _v.Rewards = append(_v.Rewards, _list_v_)
                }
            }

    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["vip"].(float64); !_ok_ { err = errors.New("vip error"); return }; _v.Vip = int32(_tempNum_) }
    { var _ok_ bool; if _v.Desc, _ok_ = _buf["desc"].(string); !_ok_ { err = errors.New("desc error"); return } }
    return
}

func DeserializeSignsignCheckIn(_buf map[string]interface{}) (*SignsignCheckIn, error) {
    v := &SignsignCheckIn{}
    if err := v.Deserialize(_buf); err == nil {
        return v, nil
    } else {
        return nil, err
    }
}
