//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig

type SignTbSign struct {
    _dataMap map[int32]*Signsign
    _dataList []*Signsign
}

func NewSignTbSign(_buf []map[string]interface{}) (*SignTbSign, error) {
	_dataList := make([]*Signsign, 0, len(_buf))
	dataMap := make(map[int32]*Signsign)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeSignsign(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &SignTbSign{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SignTbSign) GetDataMap() map[int32]*Signsign {
    return table._dataMap
}

func (table *SignTbSign) GetDataList() []*Signsign {
    return table._dataList
}

func (table *SignTbSign) Get(key int32) *Signsign {
    return table._dataMap[key]
}


