
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


import "errors"

type SignsignPatch struct {
    Id int32
    Costs []*ItemItemRC
    Vip int32
}

const TypeId_SignsignPatch = -2125117030

func (*SignsignPatch) GetTypeId() int32 {
    return -2125117030
}

func NewSignsignPatch(_buf map[string]interface{}) (_v *SignsignPatch, err error) {
    _v = &SignsignPatch{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_costs__ interface{}; if __json_costs__, _ok_ = _buf["costs"]; !_ok_ || __json_costs__ == nil { err = errors.New("costs error"); return } else { var __x__ []*ItemItemRC;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_costs__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*ItemItemRC, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *ItemItemRC
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewItemItemRC(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Costs = __x__ }}
    { var _ok_ bool; var __json_vip__ interface{}; if __json_vip__, _ok_ = _buf["vip"]; !_ok_ || __json_vip__ == nil { err = errors.New("vip error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_vip__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Vip = __x__ }}
    return
}

