//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig

import "errors"

type SignsignPatch struct {
    Id int32
    Costs []*ItemItemRC
    Vip int32
}

const TypeId_SignsignPatch = -2125117030

func (*SignsignPatch) GetTypeId() int32 {
    return -2125117030
}

func (_v *SignsignPatch)Deserialize(_buf map[string]interface{}) (err error) {
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
     {
                var _arr_ []interface{}
                var _ok_ bool
                if _arr_, _ok_ = _buf["costs"].([]interface{}); !_ok_ { err = errors.New("costs error"); return }

                _v.Costs = make([]*ItemItemRC, 0, len(_arr_))
                
                for _, _e_ := range _arr_ {
                    var _list_v_ *ItemItemRC
                    { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v_ error"); return }; if _list_v_, err = DeserializeItemItemRC(_x_); err != nil { return } }
                    _v.Costs = append(_v.Costs, _list_v_)
                }
            }

    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["vip"].(float64); !_ok_ { err = errors.New("vip error"); return }; _v.Vip = int32(_tempNum_) }
    return
}

func DeserializeSignsignPatch(_buf map[string]interface{}) (*SignsignPatch, error) {
    v := &SignsignPatch{}
    if err := v.Deserialize(_buf); err == nil {
        return v, nil
    } else {
        return nil, err
    }
}
