
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


type SignTbSignCheckIn struct {
    _dataMap map[int32]*SignsignCheckIn
    _dataList []*SignsignCheckIn
}

func NewSignTbSignCheckIn(_buf []map[string]interface{}) (*SignTbSignCheckIn, error) {
    _dataList := make([]*SignsignCheckIn, 0, len(_buf))
    dataMap := make(map[int32]*SignsignCheckIn)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSignsignCheckIn(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SignTbSignCheckIn{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SignTbSignCheckIn) GetDataMap() map[int32]*SignsignCheckIn {
    return table._dataMap
}

func (table *SignTbSignCheckIn) GetDataList() []*SignsignCheckIn {
    return table._dataList
}

func (table *SignTbSignCheckIn) Get(key int32) *SignsignCheckIn {
    return table._dataMap[key]
}


